### ISSUE TITLE
Could not load file or assembly 'MaterialDesignColors, Culture=neutral' or one of its dependencies

### ISSUE THREAD

**Issue by Arshad8464** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#980] opened 2018-07-09 06:14 UTC
Hi am getting the following error when running my class library project.

>  "Could not load file or assembly 'MaterialDesignColors, Culture=neutral' or one of its dependencies. The system cannot find the file specified.":"MaterialDesignColors, Culture=neutral"}	System.Exception {System.IO.FileNotFoundException 

I tried the below link forthe issue [ Could not load file or assembly 'MaterialDesignThemes.Wpf ](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/427) and the issue got fixed by adding the piece of code suggested as below .
```
   public partial class UserControl1 : UserControl
    {
        public UserControl1()
        {
            InitializeComponent();
            ShadowAssist.SetShadowDepth(this, ShadowDepth.Depth0);
        }
    }

```

Is there any fix like above available for `MaterialDesignColors.dll ? 

**Note : All the dlls exists in same folder.**

**Comment by Streissi** [comment] 2018-07-12 09:35
it would be interesting which dependency you could not load. Can you specify more detailed information. You can catch a ReflectionTypeLoadException. There is a Types property, which lists all types they could not be loaded.

**Comment by Arshad8464** [comment] 2018-07-13 10:49
I have added MaterialDesignColors.dll and used in my application .But when running getting an error as Could not load file **MaterialDesignColors.dll**

**Comment by Keboo** [comment] 2018-07-13 21:53
@Arshad8464 take a look at [Fuselofvw](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) for debugging assembly resolution errors (example of using it [here](https://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx)). There are many reasons why this error could occur. The most common is a version mismatch from the version of MaterialDesignColors.dll that your app was compiled against and the one sitting in the directory. The other time this occurs is when this library is used as part of an extension for some other application.

**Comment by 2adicted** [comment] 2018-07-15 18:56
Hi! I am interested if you can elaborate on this statement "The other time this occurs is when this library is used as part of an extension for some other application." I am trying to use MaterialDesignThemes in a class library. I am able to reference it correctly, but I get the same error as the original poster. Thank you.

**Comment by quicoli** [comment] 2018-07-15 19:57
I use with prism in the following way:

My shell has the nuget reference to material design xaml library and in the
app.xaml I set it up.

My modules also have nuget reference to material design xaml lib. As you
know, UI modules are wpf usercontrols, so in each page I include the
material design xaml as resource. This allows me to see styles in design
time.

When I deploy my modules everything is loaded correctly.

There's no duplicate resources because I use a specialized resource class
to load resources only in design time in my modules.

**Comment by z3ke1r** [comment] 2018-10-09 19:43
I had the same error and used the code below modeled after your themes solution and that did the trick for me.

`var hue = new Hue("Dummy", Colors.AliceBlue, Colors.AntiqueWhite);`

**Comment by Keboo** [comment] 2019-04-11 17:15
@JovanovicMarija there is not really a single solution. As the error indicates the issue is the running process is unable to locate the assembly. Can you provide more detail on what type of app this is, how your projects reference each other, and which ones are referencing the material design library.

**Comment by JovanovicMarija** [comment] 2019-04-12 09:02
The problem might be Revit and the way it's loading dlls. I introduced the following code
```AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;``` and
```
Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
{
    if (args.Name.Contains("MaterialDesignTheme"))
    {
        string filename = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

        filename = Path.Combine(filename, "MaterialDesignTheme.Wpf.dll");

        if (File.Exists(filename))
        {
            return Assembly.LoadFrom(filename);
        }
    }
    return null;
}
```
But now i get the error:
```
System.Windows.Markup.XamlParseException: ''Set property 'System.Windows.ResourceDictionary.Source' threw an exception.'

FileNotFoundException: Could not find file 'MaterialDesignTheme.Wpf.resources'.
```
I have found this [github issue ](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/337) that faces the same problem, but his app runs and my app chrashes.

**Comment by Keboo** [comment] 2019-04-12 16:47
@JovanovicMarija ah so this is being loaded as part of an extension. Dynamic [assembly loading](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies) can be quite tricky. The code you have above is only attempting to load the `MaterialDesignTheme.Wpf.dll` but it is ignoring the `MaterialDesignColors.dll` which you will need to load as well.

**Comment by JovanovicMarija** [comment] 2019-04-23 14:09
@Keboo i apologise for my late response. My second post was only one of many quick&dirty ways i tried in order to solve the problem, i should have posted the code that covers loading MatreialDesignColors as well (yet the error message would have been the same).
What solved my problem was completely abendoning the code snipped from my second post and doing what @Arshad8464 and @z3ke1r did.
I didn't originally understand that this approach would solve the problem, because i was trying to follow MVVM pattern and keep code behind clean. Therefore it didn't make any sense to me that they were suggesting to put bullshit code in the file that i was trying to keep empty. But hey, it works now! :)

**Comment by Keboo** [comment] 2019-04-23 16:24
Closing for now as all of the issues appear to be outside of this library. Let me know if there is more that needs to be addressed here.

**Closed by Keboo** 2019-04-23 16:24 UTC

**Comment by mswaidan** [comment] 2019-05-23 16:13
For folks still encountering this issue: [this post](https://www.carlosjanderson.com/beautify-your-wpf-apps-with-material-design/) by Carlos Anderson explains what's going on:

> There’s another tricky thing. Because you don’t use any classes in the Material Design assemblies, your script assembly doesn’t load those assemblies. It’s the XAML parser that uses the Material Design assemblies and therefore tries to load them. The problem is that, because it’s not your assembly that loads them, .NET looks for the Material Design assemblies in the wrong place.

And provides a solution similar to what @z3ke1r suggests: 
```
public MainWindow()
{
    InitializeMaterialDesign();
    InitializeComponent();
}
 
private void InitializeMaterialDesign()
{
    // Create dummy objects to force the MaterialDesign assemblies to be loaded
    // from this assembly, which causes the MaterialDesign assemblies to be searched
    // relative to this assembly's path. Otherwise, the MaterialDesign assemblies
    // are searched relative to Eclipse's path, so they're not found.
    var card = new Card();
    var hue = new Hue("Dummy", Colors.Black, Colors.White);
}
```

This solved it for me.

**Comment by jespersh** [comment] 2019-05-23 16:47
@mswaidan does that also work in release builds? I'm using some code at work that also requires me to reference the Colors dll and do a noop call because a method like yours gets optimized away.

**Comment by mswaidan** [comment] 2019-05-23 17:00
@jespersh Just checked, and that solution works on my project's release build. This is definitely at the edges of my understanding though, so can't say whether it will work in other cases.

**Comment by jespersh** [comment] 2019-05-23 19:18
Found it again. If @mswaidan's suggestion doesn't work, try this (from https://stackoverflow.com/a/39755840):
```C#
Action<Type> noop = _ => {};
var dummy = typeof(Card);
noop(dummy);
```

You'd need the same for the Color dll (Hue for example)

**Comment by hedinjke** [comment] 2019-09-25 08:34
Hi. I tried everything from this discussion... And finally i still getting an error.
![image](https://user-images.githubusercontent.com/43303353/65583190-6f284580-df87-11e9-9483-742b0bd9c87c.png)

The only solution i found is to put MaterialDesign libraries into Revit app folder. (C:\Program Files\Autodesk\Revit 2017). I tried to load these libraries at runtime with but still got same exception. Does anybody knows any better solution?

**Comment by hedinjke** [comment] 2019-09-25 14:45
Finally found solution. 

May be this gonna help someone. Here is it:
``` csharp
public class AssemblyLoader: IDisposable {
 private static string ExecutingPath => Assembly.GetExecutingAssembly().Location;

 public AssemblyLoader() {
  LoadAll();
 }
 private static void LoadAll() {
  AppDomain.CurrentDomain.AssemblyResolve += LoadMaterialDesign;
 }

 private static Assembly LoadMaterialDesign(object sender, ResolveEventArgs args) {
  if (null == ExecutingPath) return null;
  string assemlyToLoad = string.Empty;

  string GetAssemblyName(string fullName) => fullName.Substring(0, fullName.IndexOf(','));

  var path = ExecutingPath;
  var dir = new FileInfo(path).Directory;

  var assemblies = from file in dir.EnumerateFiles()
  where file.Name.EndsWith(".dll") ||
   file.Name.EndsWith(".exe")
  select Assembly.LoadFrom(file.FullName);

  foreach(var assembly in assemblies) {

   var assemName = GetAssemblyName(assembly.FullName);
   var requested = GetAssemblyName(args.Name);

   try {
    if (assemName == requested) {
     return assembly;
    }
   } catch (Exception) {
    continue;
   }

   //}
  }
  return null;
 }

 void IDisposable.Dispose() {
  AppDomain.CurrentDomain.AssemblyResolve -= LoadMaterialDesign;
 }
}
```
Usage example:
``` csharp
[Transaction(TransactionMode.Manual)]
public class Command : IExternalCommand
{
	public Result Execute(ExternalCommandData commandData,
							  ref string message,
							  ElementSet elements)
	{
		using var loader = new 
		return Result.Succeeded();
	}
}
```

**Comment by jespersh** [comment] 2019-09-25 15:23
@hedinjke could you also make it a gist?

**Comment by hedinjke** [comment] 2019-09-25 17:18
@jespersh yes, of course. If i understood you right... Here is it. I'm sorry, but i'm new in C#, Git and english skills... So if u help me to improve anything here would be awesome :)
https://gist.github.com/hedinjke/24908f66da704b06eba743f58fb1713d

**Comment by xHatti** [comment] 2019-10-10 10:28
Got the same issue on several machines. Even with a complete fresh installation. Even the demo projects wont work and throw following error on debug:

`FileLoadException: Die Datei oder Assembly "MaterialDesignThemes.Wpf, Version=1.0.7222.22334, Culture=neutral, PublicKeyToken=38dcbcee103a64ec" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
`
Only happens with newest 2.6. version.
Older 2.5 version i was using is working fine in my product and the demo projects are working.

**Comment by Keboo** [comment] 2019-10-10 19:37
@xHatti can you check and see if you have any [binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element) in your [appconfig](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/)?

These may need to be removed or updated to the latest version.

**Comment by xHatti** [comment] 2019-10-14 10:49
@Keboo Thanks for reply.
No there is no binding redirect present. Not in the project or in machine.config
The workarround from @hedinjke is working fine for me. But as said, even the 2.6.0 Release source code isnt working for me in debug mode with a fresh system and fresh vs2017

fuslogvw showed me, that it searches for "MaterialDesignThemes.Wpf, Culture=neutral" which can be found in the debug folder of the project. But it also searches for "MaterialDesignThemes.Wpf, Version=1.0.7226.18106, Culture=neutral, PublicKeyToken=38dcbcee103a64ec" which cant be found/mismatch with the revision number of the dll in debug folder.

Fuslog says, it only found "MaterialDesignThemes.Wpf, Version=1.0.7226.22802, Culture=neutral, PublicKeyToken=38dcbcee103a64ec." in debug folder.

After that, fuslog shows me that it wants to load 2 resource.dll for materialdesign
"MaterialDesignThemes.Wpf.resources, Version=1.0.7226.22802, Culture=de, PublicKeyToken=38dcbcee103a64ec"

and the other is almost the same but with Culture "de-DE"
but both cant be found either.

**Comment by hedinjke** [comment] 2019-10-14 11:24
@xHatti first of all u don't need to check version number inside assembly resolve event. And u don't need to load .resources files, u should return null. [Here is](https://gist.github.com/hedinjke/24908f66da704b06eba743f58fb1713d) the updated version of my solution.

**Comment by FriedrichRehren** [comment] 2019-12-19 11:39
@Arshad8464 Solving it was pretty simple. Just Install MaterialDesignColors over NuGet as well

**Comment by imckl** [comment] 2019-12-22 01:55
> @Arshad8464 @Keboo Solving it was pretty simple. Just Install MaterialDesignColors over NuGet as well

Use version 3.0.0 in WPF and this works

**Comment by DeanMauro** [comment] 2020-02-14 13:13
For anyone using this library in a Visual Studio extension, you have to do two things:

1) Sign the assembly (necessary for all VSIX dependencies). The easiest way is using the [StrongNamer](https://github.com/dsplaisted/strongnamer) package. Just add it to your project as a reference and it will sign all unsigned dependencies at build time. No further setup needed.
2) Add the `[ProvideBindingPath]` attribute to extension's `Package` or `AsyncPackage` file. This tells your XAML files to look at all the project's references.

**Comment by naldorp** [comment] 2020-04-27 15:42
> For anyone using this library in a Visual Studio extension, you have to do two things:
> 
> 1. Sign the assembly (necessary for all VSIX dependencies). The easiest way is using the [StrongNamer](https://github.com/dsplaisted/strongnamer) package. Just add it to your project as a reference and it will sign all unsigned dependencies at build time. No further setup needed.
> 2. Add the `[ProvideBindingPath]` attribute to extension's `Package` or `AsyncPackage` file. This tells your XAML files to look at all the project's references. [See here for more details.](https://stackoverflow.com/questions/4478853/vsx-2010-package-loading-markup-xaml-parsing-cannot-find-assemblies)

I've spent so many hours trying to fix this. Thank you.

**Comment by R3ap4r** [comment] 2020-05-16 12:58
Since it's a reference error, i checked to see what could be a possible solution.

All i did was:

Right click your project
Select Add --> Reference

In the menu Assemblies make sure Accessibility is activated.

That's it, everything is working.

**Comment by finti3295** [comment] 2020-06-16 14:10
I had a similar problem that I resolved by removing any implicit initialization of all the wpf controls containing material design reference and group there initialization into a function "Initialize" that I call one time before using my controls

**Comment by Razique** [comment] 2021-01-23 05:58
Hi,
I encountered the same issue while attempting to load an application. 
I built upon @hedinjke's good work by removing unnecessary calls to the `Assembly.LoadFrom()` method. I noticed that your suggestion would lead to many unnecessary calls - in my case, the same assembly would be loaded 16 times or so.

Instead of using a `foreach`structure to iterate over the list of assemblies returned by:
```csharp
var assemblies = from file in dir.EnumerateFiles()
    where file.Name.EndsWith(".dll") ||
    file.Name.EndsWith(".exe")
    select Assembly.LoadFrom(file.FullName);
```

I return a list of strings and use LINQ expressions to compare between the assemblies already loaded, and the ones required by the `AppDomain.CurrentDomain.AssemblyResolve` event.

- If the assembly is already loaded, we return it, as expected by the event
- If the assembly is not loaded, *and* requested *and* present in the list of files, we return it via `return Assembly.LoadFrom(assemblyToLoad);`
- If the assembly is not loaded, *and* requested, but missing from the build directory, we return null.

`AssemblyLoader.cs`
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;

namespace App.Namespace
{
    /// <summary>
    /// Used to determine the UNC path of the solution files (on the file system)
    /// and load the assembly
    /// </summary>
    public class AssemblyLoader : IDisposable
    {
        private static string _executingPath;
        public AssemblyName _assemblyName;

        private DirectoryInfo _fileInfo;
        private IEnumerable<string> _assemblies;

        readonly AppDomain currentDomain = AppDomain.CurrentDomain;

        private IEnumerable<Assembly> _domainAssemblies;

        /// <summary>
        /// Default constructor
        /// </summary>
        public AssemblyLoader()
        {
            // Store the loaded assemblies
            _executingPath = Assembly.GetExecutingAssembly().Location;
            _fileInfo = new FileInfo(_executingPath).Directory;

            // Return a list of all DLLS from the executing directory
            _assemblies = EnumerateFiles.GetFiles(_fileInfo);
            _domainAssemblies = currentDomain.GetAssemblies().Where(a => !a.IsDynamic);

            AppDomain.CurrentDomain.AssemblyResolve += LoadApplicationAssemblies;
        }

        /// <summary>
        /// Event handler to return an assembly
        /// </summary>
        /// <param name="sender">The object that raises the event</param>
        /// <param name="args">Supplementary parameters</param>
        /// <returns>The name of the a assembly</returns>
        public Assembly LoadApplicationAssemblies(object sender, ResolveEventArgs args)
        {
            if (string.IsNullOrEmpty(_executingPath))
                return null;

            try
            {
                // Ignore missing resources
                if (args.Name.Contains(".resources"))
                    return null;

                // Check for assemblies already loaded
                Assembly loadedAssembly = _domainAssemblies.FirstOrDefault(x => x.FullName == args.Name);
                if (loadedAssembly != null)
                    return loadedAssembly;

                var requestedAssembly = args.Name.Split(',')[0];
                var assemblyToLoad = _assemblies.Where(x => x.Contains(requestedAssembly)).FirstOrDefault();

                return Assembly.LoadFrom(assemblyToLoad);
            }

            catch (Exception e)
            {
                // or rethrow the exception
                // throw;
                return null;
            }
        }

        public void Dispose()
        {
            AppDomain.CurrentDomain.AssemblyResolve -= LoadApplicationAssemblies;
        }
    }
}
```

`EnumerateFiles.cs`
``` csharp
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace App.Namespace
{
    /// <summary>
    /// Return a list of DLLs in-use by the project. See the <see cref=AssemblyLoader"/> class
    /// for an example
    /// </summary>
    class EnumerateFiles
    {
        /// <summary>
        /// Return the list of files in fileInfo
        /// </summary>
        /// <param name="fileInfo">The directory</param>
        /// <returns>A read-only enumerable (list) that contains a list of files in use</returns>
        public static IEnumerable<string> GetFiles(DirectoryInfo fileInfo)
        {
            return from file in fileInfo.EnumerateFiles()
                   where (file.Name.EndsWith(".dll") || file.Name.EndsWith(".exe"))
                   select file.FullName;
        }
    }
}
```

**Comment by M3rtix** [comment] 2023-01-10 19:57
> Since it's a reference error, i checked to see what could be a possible solution.
> 
> All i did was:
> 
> Right click your project Select Add --> Reference
> 
> In the menu Assemblies make sure Accessibility is activated.
> 
> That's it, everything is working.

Thanks for your help !

**Comment by KonradZaremba** [comment] 2023-01-25 12:57
Hi, guys thanks to @hedinjke and  @Razique  for a solution. I have managed to load styles from MaterialDesign to Revit add and it works fine. However, I have a problem with element behaviours. Since I don't have App.xaml in the Revit addon I have put all the resources in Dictionary and load directly to UserControls. I have an issue with materialDesign:DataGridComboBoxColumn it binds the selected value fine, however when clicked all the functionality of combobox doesn't work and only a white square around the cell appears  (+ the cell goes blank). Binding works on a standalone version with MaterialDesign added to ResourceDictonary in App.xaml (like it should be according to documentation) however it doesn't when put to Resources.xaml and added to UserControls(which seemed a good workaround when I don't build a separate app). Would you happen to have any solution to such a problem?

**Comment by Razique** [comment] 2023-01-25 21:40
@KonradZaremba do you have a screenshot and sample code to reproduce the issue?

**Comment by KonradZaremba** [comment] 2023-02-08 10:33
@Razique  Sorry for the late response I missed the notification. In the meantime, I have double-checked. And I'm sure that reason for causing this problem is instead putting resources, not in App.xaml. It is giving the same result on pure WPF applications as well. Here is a screenshot how it looks:

1. Dictionary placed in Window or Page
![comboboxbug](https://user-images.githubusercontent.com/18317435/217504441-9fa65039-8ab7-4585-8d29-2eecfd296aba.jpg)

2. Dictionary placed in App.xaml
![comboboxexpected](https://user-images.githubusercontent.com/18317435/217504452-e70f9489-1d28-400c-8024-c72fdb6c0de6.jpg)

Is there any way to put MaterialDesing reference in Window or Page and initialize combobox elements properly?

**Comment by Keboo** [comment] 2023-02-09 04:25
@KonradZaremba putting the resources in App.xaml is not a requirement. Typically, it is just recommended to put them at the "root level" but that could be a `Page` or a `Window`. Your solution above with putting it in a resource dictionary should work. Any chance the repository is open source and you can share it?

**Comment by KonradZaremba** [comment] 2023-02-09 22:12
@Keboo Yes, I have isolated further to the pure WPF version. In this stage, it should reproduce the issue. In App.xaml I have left lines to comment out. If you do so comobox is working. Thanks for having a look. https://github.com/DesignboticTeam/MaterialDesignBug

**Comment by Keboo** [comment] 2023-02-12 23:47
@KonradZaremba thanks for the repository. I have tracked down the source of the problem. The issue is with how the DataGridComboBoxColumn is implemented, specifically its [ElementStyle and EditingElementStyle properties](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/DataGridComboBoxColumn.cs#L43-L67). Both of these properties attempt to use `TryFindResource` from a `ComboBox` element that is not connected to the visual tree so it ends up only searching from the root application. This is the reason for the behavior that you are seeing. I will look into ways of trying to fix this in the future, but a simple solution is not immediately apparent. 

However, with that said, you can work around the issue. The Material Design `DataGridComboBoxColumn` is just a convenience class that wraps the regular WPF `DataGridComboBoxColumn`. So you can simply go back to using the regular WPF `DataGridComboBoxColumn`. You will need to set a few additional properties on the column, as well as manually setup the `ItemsSource` binding within those styles. I will open a PR onto your sample repository as well, but just documenting the solution here as well:

```xaml
<DataGrid
    AutoGenerateColumns="False"
    CanUserAddRows="False"
    HeadersVisibility="All"
    ItemsSource="{Binding DummyObjects}"
    SelectionMode="Single">
    <DataGrid.Resources>
        <Style
            x:Key="ComboboxDataGridCellStyle"
            BasedOn="{StaticResource {ComponentResourceKey TypeInTargetAssembly={x:Type ComboBox},
                                                            ResourceId=MaterialDataGridComboBoxColumnStyle}}"
            TargetType="ComboBox">
            <Setter Property="ItemsSource" Value="{Binding ComboBoxOptions}" />
        </Style>

        <Style
            x:Key="ComboboxDataGridCellEditingStyle"
            BasedOn="{StaticResource {ComponentResourceKey TypeInTargetAssembly={x:Type ComboBox},
                                                            ResourceId=MaterialDataGridComboBoxColumnEditingStyle}}"
            TargetType="ComboBox">
            <Setter Property="ItemsSource" Value="{Binding ComboBoxOptions}" />
        </Style>
    </DataGrid.Resources>

    <DataGrid.Columns>

        <DataGridTextColumn
            Width="100"
            Binding="{Binding Name}"
            EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnEditingStyle}"
            ElementStyle="{StaticResource MaterialDesignDataGridTextColumnStyle}"
            Header="Name" />
        <DataGridComboBoxColumn
            Width="180"
            EditingElementStyle="{StaticResource ComboboxDataGridCellEditingStyle}"
            ElementStyle="{StaticResource ComboboxDataGridCellStyle}"
            Header="Combobox"
            SelectedValueBinding="{Binding SelectedComboBoxOptions}" />
    </DataGrid.Columns>

</DataGrid>
```

**Comment by KonradZaremba** [comment] 2023-02-13 08:50
Thanks a lot. As for plan B, I was thinking about using regular combos. But I haven't thought about binding them with MD styles. I have marge pull.
