### ISSUE TITLE
XDG0012	The member "XXX" is not recognized or is not accessible.

### ISSUE THREAD

**Issue by netcorefan1** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1758] opened 2020-04-22 19:18 UTC
To reproduce build the source project and then open Fields.xaml from MaterialDesignDemo project.
The errors shown in the picture will appears. The project compiles and runs just fine, but the errors breaks the designer.
VS 16.5.4
<img width="667" alt="MemberNotRecognized" src="https://user-images.githubusercontent.com/63934725/80099699-2feac300-856f-11ea-8103-55a143f000fd.png">

**Comment by soi013** [comment] 2020-04-24 00:08
duplicate of #730

**Comment by Keboo** [comment] 2021-09-24 16:44
Unfortunately this is a Visual Studio issue and not something easily solved in this library.

**Closed by Keboo** 2021-09-24 16:44 UTC
Labels: duplicate, Out of scope
