### ISSUE TITLE
How to set foreground brush to "PART_ClearButton"

### ISSUE THREAD

**Issue by bezzad** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2018] opened 2020-08-11 17:59 UTC
I have TextBox with the `MaterialDesignOutlinedTextFieldTextBox` styles which has `ClearButton`. Now I want to set `ClearButton` foreground of TextBox, But I can't find any option in `materialDesign:TextFieldAssist` to set brush.
Please help me, what can I do?

This is my textbox:

```xaml
<TextBox Grid.Row="1" Padding="0 -5 0 0" Margin="10" 
         materialDesign:ValidationAssist.Background="Transparent"
         materialDesign:ValidationAssist.HorizontalAlignment="Right"
         materialDesign:TextFieldAssist.HasClearButton="True"
         materialDesign:HintAssist.IsFloating="False"
         materialDesign:HintAssist.Hint="{x:Static shared:Resources.PhoneOrEmail}"
         materialDesign:HintAssist.Foreground="{DynamicResource Brushes.Highlight}"
         materialDesign:HintAssist.Background="{DynamicResource Brushes.ThemeBackground}"
         Text="{Binding Model.Username, UpdateSourceTrigger=PropertyChanged}" 
         Style="{StaticResource MaterialDesignOutlinedTextFieldTextBox}"
         VerticalContentAlignment="Center" 
         TextAlignment="Center" FlowDirection="LeftToRight" >
    <TextBox.Resources>
        <Style TargetType="{x:Type materialDesign:SmartHint}">
            <Setter Property="HorizontalAlignment" Value="Center"/>
        </Style>
    </TextBox.Resources>
</TextBox>
```

**Comment by Keboo** [comment] 2020-08-12 07:21
There is not currently a direct setter for it. However you can override the theme brush for it by specifying a brush with the key `MaterialDesignToolForeground`. Like this:
```xaml
<TextBox Style="{StaticResource MaterialDesignOutlinedTextFieldTextBox}"
            VerticalAlignment="Center"
            materialDesign:TextFieldAssist.HasClearButton="True">
    <TextBox.Resources>
        <SolidColorBrush x:Key="MaterialDesignToolForeground" Color="Red" />
    </TextBox.Resources>
</TextBox>
```

**Comment by bezzad** [comment] 2020-08-15 05:51
Unfortunately, this code did not work!

![why](https://user-images.githubusercontent.com/10928710/90306305-0ae4dc00-dee1-11ea-993a-831f5d1f16d9.PNG)

**Comment by Keboo** [comment] 2020-08-18 04:10
@bezzad I might need some more information on the project. It appears from your screenshot that the clear button is not actually being displayed inside of that TextBox. What language is being set there? I am wondering if perhaps the RightToLeft formatting is causing issues.

**Comment by bezzad** [comment] 2020-08-18 06:58
Yes, my application language Persian which is Right To Left. The clear button has been displayed but that foreground colour is the almost same as the background.

**Comment by Keboo** [comment] 2020-08-18 19:48
@bezzad I will probably need a sample project. Right now I am not able to reproduce the screenshot that you showed above. 
Have you tested with the latest 3.2.0 _preview_ NuGet package to see if it is still a problem?

**Comment by Keboo** [comment] 2021-09-24 21:34
Closing for now. If more information is provided on reproducing the issue we can reopen

**Closed by Keboo** 2021-09-24 21:34 UTC
Labels: question
