### ISSUE TITLE
Bug with alternate style in demo

### ISSUE THREAD

**Issue by plainerman** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#538] opened 2016-11-04 20:56 UTC
Concerning file: MaterialDesignInXamlToolkit/MahMaterialDragablzMashUp/PaletteSelectorViewModel.cs
Concerning function: private static void ApplyStyle(bool alternate)

Steps to reproduce issue:

1..Drag out tab
2..Change (in UI) theme to alternate
3..Drag tab back in

Result / Issue: 
dragged tab has the old (non alternate) style again

Fix:
`
    private static void ApplyStyle(bool alternate)

	Application current = Application.Current;

	var styleKey = alternate ? "MaterialDesignAlternateTabablzControlStyle" : "MaterialDesignTabablzControlStyle";

	var style = current.TryFindResource(styleKey) as Style;

	current.Resources[typeof(TabablzControl)] = style;
`

**Comment by greuelpirat** [comment] 2020-05-02 16:24
Could not reproduce

![538-drag-alternate-style](https://user-images.githubusercontent.com/16866222/80869678-17328980-8ca2-11ea-95ce-ee8036752e49.gif)

**Comment by Keboo** [comment] 2020-05-03 22:33
I suspect this was fixed with the 3.1.0 release. Closing for now.

**Closed by Keboo** 2020-05-03 22:33 UTC
Labels: bug, up-for-grabs
