### ISSUE TITLE
tab1.Visibility Hidden not work

### ISSUE THREAD

**Issue by mammadkoma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1713] opened 2020-03-27 07:31 UTC
Hi and thank you
in this your sample visibility for TabItem by c# code not work : https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/MainWindow.xaml

private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            tab2.Visibility = Visibility.Hidden; // not work
            tab3.IsSelected = true;
        }
How can we hide a TabItem by c# code?

**Comment by soi013** [comment] 2020-03-27 11:54
It is Dragablz`s issue.

https://github.com/ButchersBoy/Dragablz/issues/239

https://github.com/ButchersBoy/Dragablz/issues/91

**Comment by Keboo** [comment] 2020-03-27 16:58
Closing this issue since the problem is over in the Dragablz library.

**Closed by Keboo** 2020-03-27 16:59 UTC
