### ISSUE TITLE
Fast switching between TransitionSlides causes content to disappear!

### ISSUE THREAD

**Issue by mhmd98** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#975] opened 2018-06-24 14:46 UTC
Hi, i found an issue in transitions when fast switching between 2 slides.
the issue occurs when I switch to a different slide while the animation from the first slide isn't finished. that causes the content to disappear, clicking again on the button doesn't show the content but switching to a different slide and going back works. The issue is present in the demo if you switch fast between the slides in the transaction pages (as shown in the GIF).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/27295078/41820149-49900862-77cd-11e8-9db0-f6078fb448e2.gif)

**Comment by mhmd98** [comment] 2018-06-25 09:16
an easier way to reproduce the issue would be by changing the selectedindex immediately but putting it in the same method for example:
        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            MainTransitioner.SelectedIndex = 1;
            MainTransitioner.SelectedIndex = 0;
        }

**Comment by jespersh** [comment] 2018-06-25 09:36
Dupe of issue 939 my friend. Granted nothing searched on that particular issue would have made it show up

**Comment by mhmd98** [comment] 2018-06-26 12:33
well i went back to the demo to investigate further... i find it really weird that clicking on the blank would cause content to disappear cause it won't fire any event so there is no reason why it would do that, i also noticed that for both me and the creator of Issue #939 first switch did nothing!
so here is what i found out:
1. fast switching between 2 slides causes the content to disappear as i described above.
2. clicking on the blank doesn't cause the content to disappear (or anything else for that matter), the reason issue #939 exist is because clicking the blank that fast would mean fast transitioning between the slides which leads to the first point.
3. The issues happens only after first try (I went back and tested that). So if i start the program and switch fast between 2 slides the content does **not** disappear but after that it does. so i restart the program and fast-switch the content won't disappear if i do it one more time it will disappear.
I hope this will help locating the issue.

**Closed** 2022-11-14 06:56 UTC
Labels: bug
