### ISSUE TITLE
Card has slight top and left gap before content

### ISSUE THREAD

**Issue by MrMitch** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#729] opened 2017-06-13 22:41 UTC
When using the Card component, i see a slight top and left gap between the border of the card and the begining of its content.
This behavior doesn't happen in VS designer, only when the app is run outside of it.

# Designer
![image](https://user-images.githubusercontent.com/576772/27107746-10418bcc-509a-11e7-90d5-4f21d8440312.png)

# Real app
![image](https://user-images.githubusercontent.com/576772/27107774-32f95fb4-509a-11e7-80c8-c41949077c91.png)

**Comment by spiegelp** [comment] 2017-06-17 11:21
I have the same issue in one of my apps too. However if I resize the window, the gap will appear or disappear. 

I just played around with the demo and it has the same behavior. First there is no gap between the top and the content. After resizing the window width the second card got into the next line and a gap appears: 
![cardgap](https://user-images.githubusercontent.com/6129929/27252406-22344ac4-535e-11e7-8a4a-3b4053dc7e32.png)

I did not find any bugs in a short code review some months ago. So I thought that the WPF rendering was not pixel-perfect and I did not care about it anymore.

**Comment by bebenins** [comment] 2017-06-17 11:49
In my case it comes and goes without any changes to XAML.  But most of the official builds it looks correct.  Not sure what's causing it.

**Comment by andybond006** [comment] 2017-06-20 20:12
Possibly related to #678?

**Comment by CookiesAndCoffee** [comment] 2017-08-23 13:18
I have noticed that when I increase the lenght of a card, the pixel gap occurs every 2nd pixel.

**Comment by Keboo** [comment] 2021-09-24 06:21
The issue with every 2nd pixel is caused by layout rounding. This is something that will need to be evaluated in each app and not something that can be resolved in this library.

**Closed by Keboo** 2021-09-24 06:21 UTC
