### ISSUE TITLE
Open dialog from ToolBar

### ISSUE THREAD

**Issue by kdavid9** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#841] opened 2017-11-10 05:48 UTC
Hey,

I think I found an issue, when I want to open a dialog popup from a toolbar it throws an exception with the following message: "Content cannot be passed to a dialog via the OpenDialog if DialogContent already has a binding." Of course the DialogContent property hasn't got any kind of binding and if I move the button control outside from the ToolBarTray it works fine.

```
<ToolBarTray>
     <ToolBar>
         <Button Command="{x:Static MaterialDesign:DialogHost.OpenDialogCommand}">
             <Button.CommandParameter>
                 <BusinessObjects:CommentBO />
             </Button.CommandParameter>
             <MaterialDesign:PackIcon Kind="Plus" />
         </Button>
         <Separator />
         <ListBox SelectedIndex="{Binding CommentLayoutSelectorSelectedIndex}">
             <ListBoxItem>
                 <MaterialDesign:PackIcon Kind="ViewHeadline" />
             </ListBoxItem>
             <ListBoxItem>
                 <MaterialDesign:PackIcon Kind="ViewStream" />
             </ListBoxItem>
         </ListBox>
     </ToolBar>
</ToolBarTray>
```

Best regards,
David

**Comment by Keboo** [comment] 2021-09-25 19:10
Closing for now as I am not able to reproduce from just the snippet above. I suspect I would need larger context showing the DialogHost as well.

**Closed by Keboo** 2021-09-25 19:10 UTC
