### ISSUE TITLE
PopupBox shows when is not focused.

### ISSUE THREAD

**Issue by TheAifam5** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#728] opened 2017-06-10 09:50 UTC
Using latest packages from NuGet.
- MaterialDesignColors    - 1.1.3
- MaterialDesignThemes  - 2.3.0.823

![popup-box](https://user-images.githubusercontent.com/2192274/27001818-dd70cc9a-4dd2-11e7-8f9f-cadd544864f1.gif)

**Comment by Insire** [comment] 2017-06-10 10:51
duplicate of #504 and #723

**Comment by Keboo** [comment] 2017-06-12 05:07
The [default](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L155) for many of the style for PopupBox is MouseOverEager. This opens whenever the mouse hovers over it. You might also try changing the PopupMode property.

**Closed** 2019-02-15 16:42 UTC
