### ISSUE TITLE
Inputs Validation Message Issue

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1240] opened 2019-04-23 06:38 UTC
I create a form  with two steps and when i back to prev step the second step validation messages appear on first step.

![Inputs Validation Message Issue](https://i.imgur.com/pAK94Mf.gif)

This is my xaml code for those steps:

```xaml
        <md:Transitioner Grid.Row="1"
                         Margin="0, 8, 0, 0"
                         SelectedIndex="{Binding CurrentStep}">
            <md:TransitionerSlide>
                <md:TransitionerSlide.ForwardWipe>
                    <md:SlideWipe />
                </md:TransitionerSlide.ForwardWipe>

                <StackPanel>
                    <TextBlock TextAlignment="Center">
                        <TextBox Name="TitleTextBox"
                                 Text="{Binding Title, Mode=TwoWay, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged}"
                                 Width="250"
                                 md:HintAssist.Hint="{StaticResource Title}"/>

                        <LineBreak/>
                        <LineBreak/>

                        <TextBox Name="FileNameTextBox"
                                 Text="{Binding FileName, Mode=TwoWay, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged}"
                                 Width="250"
                                 md:HintAssist.Hint="{StaticResource FileName}"/>

                        <LineBreak/>
                        <LineBreak/>

                        <TextBox Name="ColorTextBox"
                                 Text="{Binding Color, Mode=TwoWay, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged}"
                                 Width="250"
                                 md:HintAssist.Hint="{StaticResource Color}"/>

                        <LineBreak/>
                        <LineBreak/>

                        <TextBox Name="RegDateTextBox"
                                 Text="{Binding RegDate, Mode=TwoWay, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged}"
                                 Width="250"
                                 md:HintAssist.Hint="{StaticResource RegDate}"/>

                        <LineBreak/>

                    </TextBlock>

                    <Button Content="{StaticResource NextStep}"
                            Command="{Binding NextCommand}"
                            HorizontalAlignment="Right"
                            VerticalAlignment="Bottom"
                            Margin="0, 16, 24, 0">
                        <Button.Style>
                            <Style TargetType="Button"
                                   BasedOn="{StaticResource MaterialDesignOutlinedFlatButton}">
                                <Setter Property="IsEnabled" Value="False"/>
                                <Style.Triggers>
                                    <MultiDataTrigger>
                                        <MultiDataTrigger.Conditions>
                                            <Condition Binding="{Binding Path=(Validation.HasError), ElementName=TitleTextBox}" Value="False"/>
                                            <Condition Binding="{Binding Path=(Validation.HasError), ElementName=FileNameTextBox}" Value="False"/>
                                            <Condition Binding="{Binding Path=(Validation.HasError), ElementName=ColorTextBox}" Value="False"/>
                                            <Condition Binding="{Binding Path=(Validation.HasError), ElementName=RegDateTextBox}" Value="False"/>
                                        </MultiDataTrigger.Conditions>
                                        <Setter Property="IsEnabled" Value="True"/>
                                    </MultiDataTrigger>
                                </Style.Triggers>
                            </Style>
                        </Button.Style>
                    </Button>
                </StackPanel>

            </md:TransitionerSlide>

            <md:TransitionerSlide>
                <md:TransitionerSlide.BackwardWipe>
                    <md:SlideOutWipe />
                </md:TransitionerSlide.BackwardWipe>

                <StackPanel>
                    <TextBlock TextAlignment="Center">
                        <ComboBox Name="PrimaryCategoriesComboBox" 
                                  ItemsSource="{Binding PrimaryCategories}" 
                                  SelectedIndex="{Binding CurrentPrimaryCategory, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"
                                  SelectedValuePath="Key"
                                  DisplayMemberPath="Value"
                                  IsEditable="True"
                                  IsTextSearchEnabled="True"
                                  md:ComboBoxAssist.ClassicMode="True"
                                  Width="250"
                                  Margin="8 0"
                                  Padding="5"
                                  md:HintAssist.Hint="{StaticResource Category}"/>
                
                        <LineBreak/>
                        <LineBreak/>

                        <ComboBox Name="SecondaryCategoriesComboBox"
                                  ItemsSource="{Binding SecondaryCategories}" 
                                  SelectedIndex="{Binding CurrentSecondaryCategory, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"
                                  SelectedValuePath="Key"
                                  DisplayMemberPath="Value"
                                  IsEditable="True"
                                  IsTextSearchEnabled="True"
                                  md:ComboBoxAssist.ClassicMode="True"
                                  Width="250"
                                  Height="45"
                                  Margin="8 0"
                                  Padding="5"
                                  md:HintAssist.Hint="{StaticResource SubCategory}"/>                
                
                        <LineBreak/>
                        <LineBreak/>
               
                        <ComboBox Name="TertiaryCategoriesComboBox"
                                  ItemsSource="{Binding TertiaryCategories}" 
                                  SelectedIndex="{Binding CurrentTertiaryCategory, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"
                                  SelectedValuePath="Key"
                                  DisplayMemberPath="Value"
                                  IsEditable="True"
                                  IsTextSearchEnabled="True"
                                  md:ComboBoxAssist.ClassicMode="True"
                                  Width="250"
                                  Height="45"
                                  Margin="8 0"
                                  Padding="5"
                                  md:HintAssist.Hint="{StaticResource SubSubCategory}"/>

                        <LineBreak/>
                        <LineBreak/>
                        <LineBreak/>
                        <LineBreak/>

                    </TextBlock>

                    <DockPanel Margin="22, 8, 22, 0"
                               FlowDirection="LeftToRight">

                        <Button Content="{StaticResource Done}"
                                Command="{Binding NextCommand}"
                                HorizontalAlignment="Left"
                                Margin="4, 0">
                            <Button.Style>
                                <Style TargetType="Button"
                                       BasedOn="{StaticResource MaterialDesignRaisedButton}">
                                    <Setter Property="IsEnabled" Value="False"/>
                                    <Style.Triggers>
                                        <MultiDataTrigger>
                                            <MultiDataTrigger.Conditions>
                                                <Condition Binding="{Binding Path=(Validation.HasError), ElementName=PrimaryCategoriesComboBox}" Value="False"/>
                                                <Condition Binding="{Binding Path=(Validation.HasError), ElementName=SecondaryCategoriesComboBox}" Value="False"/>
                                                <Condition Binding="{Binding Path=(Validation.HasError), ElementName=TertiaryCategoriesComboBox}" Value="False"/>
                                            </MultiDataTrigger.Conditions>
                                            <Setter Property="IsEnabled" Value="True"/>
                                        </MultiDataTrigger>
                                    </Style.Triggers>
                                </Style>
                            </Button.Style>
                        </Button>

                        <Button Content="{StaticResource PrevtStep}"
                                Style="{DynamicResource MaterialDesignOutlinedFlatButton}"
                                HorizontalAlignment="Right"
                                Command="{Binding BackCommand}"
                                Margin="4, 0"/>
                    </DockPanel>
                </StackPanel>
            </md:TransitionerSlide>
        </md:Transitioner>
```

**Comment by Keboo** [comment] 2019-04-23 17:13
Hi @AmRo045 I have added some [additional documentation to the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Transitions#validation-adorners) on this. Basically the problem is that the adorner layer sits on top of the transitioner, and default validation styles use adorners, so they stay visible. The fix is pretty simply wrap the root level item  inside of your `TransitionerSlide` in an `<AdornerDecorator>` so the dorner layer will be inside of the slide rather than outside of it.

**Closed** 2019-04-24 04:39 UTC
Labels: question, wiki
