### ISSUE TITLE
Selected Item is hidden if combobox menu is open.

### ISSUE THREAD

**Issue by Madcheese101** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1513] opened 2019-11-14 09:27 UTC
Hi,
I have a problem with the combobox, when an item is selected and you open up the combobox list again the selected value is transparent and does not show up at all. 

<img width="185" alt="Capture" src="https://user-images.githubusercontent.com/40042269/68844078-dcc43880-06d1-11ea-9b1d-a5646643b84e.PNG">

**Comment by Keboo** [comment] 2019-11-14 16:09
This looks like it is probably a duplicate of #1184

**Closed** 2022-05-25 09:08 UTC
Labels: bug, duplicate
