### ISSUE TITLE
Visual Studio 2022 is unable to load MaterialDesignThemes.Wpf package.

### ISSUE THREAD

**Issue by M0n7y5** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2487] opened 2021-11-09 09:35 UTC
I upgraded to new visual studio and i instantly got bunch of errors. I can still compile just fine, but my designer is not working. 

![obrazek](https://user-images.githubusercontent.com/17201053/140898845-2ae9294b-a9ee-4baa-af58-17566921bad2.png)

I already tried few things for example:
- deleted .vs folder
- deleted obj and bin folder
- deleted local packages folder
- completely cleared nuget cache 

After all of that the issue is still here. I dont know if its package issue or Visual Studio issue.

**Comment by Keboo** [comment] 2021-11-09 15:25
Is the project open source o do you have one that reproduces this issue? I have been using Visual Studio 2022, since the previews first came out and have not encountered this problem.

**Comment by HakuSystems** [comment] 2021-11-14 16:11
same problem for me btw

**Comment by Keboo** [comment] 2021-11-14 21:47
Can you please use the Report Feedback option in Visual Studio to report this issue?

Also it would be helpful to see the XAML for the file that is causing those designer errors.

**Comment by HakuSystems** [comment] 2021-11-15 18:21
> Can you please use the Report Feedback option in Visual Studio to report this issue?
> Sure i can!
> Also it would be helpful to see the XAML for the file that is causing those designer errors.

``
<Window x:Class="newAPIAdminPanel.Auth.Login"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        xmlns:local="clr-namespace:newAPIAdminPanel.Auth"
        mc:Ignorable="d"
        Title="nanoSDKAPI"
        
        ResizeMode="NoResize"
        WindowStartupLocation="CenterOwner"
        WindowStyle="None"
        MouseDown="Window_MouseDown"
        AllowsTransparency="True"
        Height="250"
        Width="420"
        
        
        Loaded="Window_Loaded"
        TextElement.Foreground="{DynamicResource MaterialDesignBody}"
        TextElement.FontWeight="Regular"
        TextElement.FontSize="13"
        TextOptions.TextFormattingMode="Ideal" 
        TextOptions.TextRenderingMode="Auto"        
        Background="{DynamicResource MaterialDesignDarkBackground}"
        FontFamily="{DynamicResource MaterialDesignFont}"
        
        
        >
    <Border Background="{DynamicResource MaterialDesignShadowBrush}" CornerRadius="10">
        <materialDesign:TransitioningContent OpeningEffect="{materialDesign:TransitionEffect Kind=FadeIn}">
            <Grid x:Name="grid" ScrollViewer.HorizontalScrollBarVisibility="Auto" ScrollViewer.VerticalScrollBarVisibility="Auto" HorizontalAlignment="Center">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="10"/>
                    <ColumnDefinition/>
                    <ColumnDefinition Width="10"/>
                </Grid.ColumnDefinitions>
                <Grid.RowDefinitions>
                    <RowDefinition Height="10"/>
                    <RowDefinition Height="30"/>
                    <RowDefinition/>
                    <RowDefinition/>
                    <RowDefinition Height="10"/>
                </Grid.RowDefinitions>

                <StackPanel Grid.Row="1" Grid.Column="1" x:Name="DragMoveStackPanel" HorizontalAlignment="Left" VerticalAlignment="Top" Orientation="Horizontal">
                    <materialDesign:TransitioningContent OpeningEffect="{materialDesign:TransitionEffect Kind=SlideInFromTop}">
                        <StackPanel Orientation="Horizontal" Grid.Row="1" Grid.Column="1">
                            <TextBlock x:Name="HealthCheckTxt" Margin="5,0,0,0" FontSize="20" Foreground="White" TextAlignment="Center" TextWrapping="WrapWithOverflow" VerticalAlignment="Center"/>
                            <Button x:Name="CloseBtn" Click="CloseBtn_Click" Style="{DynamicResource MaterialDesignFloatingActionButton}" Height="30" Width="30" Foreground="White" Margin="195,0,0,0">
                                <Button.Content>
                                    <materialDesign:PackIcon Kind="Close"/>
                                </Button.Content>
                            </Button>
                        </StackPanel>
                    </materialDesign:TransitioningContent>
                </StackPanel>
                <StackPanel Orientation="Vertical" VerticalAlignment="Center" Grid.Row="2" Grid.Column="1" Grid.RowSpan="2">
                    <materialDesign:Card UniformCornerRadius="5" Background="{DynamicResource AttentionToActionBrush}">
                        <materialDesign:Card.Effect>
                            <DropShadowEffect ShadowDepth="1" Direction="0" Color="{DynamicResource MaterialDesignShadow}" Opacity="0.25" BlurRadius="10"/>
                        </materialDesign:Card.Effect>
                        <StackPanel>
                            <materialDesign:Card Background="{DynamicResource MaterialDesignDarkBackground}">
                                <StackPanel>
                                    <TextBlock x:Name="UserTitle" Foreground="White" Text="Username" TextWrapping="Wrap" Margin="5" VerticalAlignment="Center"/>
                                    
                                </StackPanel>
                            </materialDesign:Card>
                            <TextBox x:Name="userInput" Style="{DynamicResource MaterialDesignTextBoxBase}" materialDesign:HintAssist.Hint="John Doe" ToolTip="Enter Username or Email" Height="30" Foreground="White"/>
                            <materialDesign:Card Background="{DynamicResource MaterialDesignDarkBackground}">
                                <StackPanel Orientation="Horizontal">
                                    <TextBlock x:Name="passTitle" Foreground="White" Text="Password" TextWrapping="Wrap" Margin="5" VerticalAlignment="Center"/>
                                </StackPanel>
                            </materialDesign:Card>
                            <PasswordBox x:Name="PassInput" Style="{DynamicResource MaterialDesignPasswordBox}" materialDesign:HintAssist.Hint="2QJwygjLt3HeLuWt" ToolTip="Enter Password" Height="30" Foreground="White"/>
                            <StackPanel Orientation="Horizontal" Margin="5" HorizontalAlignment="Center">
                                <RadioButton Click="LoginBtn_Click" Margin="0,0,10,0" x:Name="LoginBtn" Style="{DynamicResource MaterialDesignChoiceChipAccentOutlineRadioButton}" Foreground="White" VerticalAlignment="Center">
                                    <RadioButton.Content>
                                        <StackPanel Orientation="Horizontal">
                                            <materialDesign:PackIcon x:Name="loginBtnIcon" Kind="LoginVariant" Foreground="White"/>
                                            <TextBlock x:Name="loginBtnContent" Text="Login" TextWrapping="Wrap" VerticalAlignment="Center" Foreground="White"/>
                                        </StackPanel>
                                    </RadioButton.Content>
                                </RadioButton>
                            </StackPanel>
                        </StackPanel>
                    </materialDesign:Card>
                </StackPanel>
            </Grid>
        </materialDesign:TransitioningContent>
    </Border>
</Window>
``

**Comment by abcentgg** [comment] 2021-11-17 14:17
Same problem, did u find the fix?

**Comment by abcentgg** [comment] 2021-11-18 17:05
@HakuSystems did u find the fix?

**Comment by HakuSystems** [comment] 2021-11-18 18:51
> @HakuSystems did u find the fix?

Nope

**Comment by Erapchu** [comment] 2021-11-25 04:30
No any problems with new project and MaterialDesignThemes.Wpf using VS 2022

**Comment by NotAsea** [comment] 2021-12-22 08:53
yeah i got same, I think that because Material didn't support visual studio 2022 yet and we whoever come , using visual studio 2022 faced this problem. There's only hope now they update in future

**Comment by MichelMichels** [comment] 2021-12-22 10:16
I had a lot of problems with VS 2022 because I upgrade my install from the preview version. I fixed everything by removing Visual Studio 2022 completely and reinstalling again. Please try this first, as I don't think this has anything to do with the project.

**Comment by HakuSystems** [comment] 2021-12-23 19:10
this solved the issue.

**Comment by MichelMichels** [comment] 2021-12-23 19:13
I'll close this issue as this is more an issue with VS than this library.

**Closed by MichelMichels** 2021-12-23 19:13 UTC
Labels: evaluation required

**Comment by MehdiElMellali** [comment] 2022-02-08 22:05
clean & rebuild and try to open MaterialDesignToolkit.Wpf.slnf

**Comment by safaenet** [comment] 2023-03-24 13:03
I faced this issue after reinstalling windows and cloning the repository again from github. I still couldnt a workaround for it. I use vs 2022 and didnt have this issue before i reinstall the windows. Even the icons cannot be displayed in xaml designer. Any solution ?

**Comment by safaenet** [comment] 2023-03-24 13:26
Since my project is in DotNet 6 , I installed NET.Desktop.Runtime.6.0.10 and it fixed my problem! This is so strange because runtime should not be related to design mode.
