### ISSUE TITLE
PopupBox closing right after opening(touch screen)

### ISSUE THREAD

**Issue by Andrewnames** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#725] opened 2017-06-05 19:06 UTC
Issue can be reproduced on MainDemo (WPF part) using touch screen device (laptop). 
 - Open Buttons and Toggles page.
- Click on PopupBox in top right corner.
- You will see that it was opened and closed right away
- if you click at the same PopupBox again, it will work as it supposed to work.
-if now you click somewhere else on the screen and try to click on PopupBox again, you will have same issue.

**Comment by Keboo** [comment] 2017-06-05 19:57
@Andrewnames I suspect this is being caused by [PopupMode being set to MouseOverEager](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L155).

Because these are based upon mouse events and not touch events it kinda makes sense that this control would fail. I suspect PopupBox (ellipsis) just to the left of that button works for you because it only relies on Click events. 

I suspect a full fix would be to properly handle the Touch events. Perhaps open a pull request if you are feeling confident in making the change?

**Comment by Keboo** [comment] 2021-09-24 06:19
Closing for now as I believe #1298 covers this issue.

**Closed by Keboo** 2021-09-24 06:19 UTC
