### ISSUE TITLE
Datagrid - column with select checkbox and select all column header

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2742] opened 2022-06-10 22:03 UTC
### Discussed in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/2739

<div type='discussions-op-text'>

<sup>Originally posted by **hahyes** June  9, 2022</sup>
Hi there,
I followed known to me way to add to Datagrid column to select datagriditems
```
            <DataGrid.RowHeaderTemplate>
                <DataTemplate>
                    <Grid>
                        <CheckBox IsChecked="{Binding Path=IsSelected, Mode=TwoWay,
                     RelativeSource={RelativeSource FindAncestor,
                      AncestorType={x:Type DataGridRow}}}"/>
                    </Grid>
                </DataTemplate>
            </DataGrid.RowHeaderTemplate>
```

In default WPF it works as intended. In MaterialDesign it is not showing anything. Is there any way to achieve similar effect without too much code? Solution above was simple enough to implement, maybe I can do this with some fixes? </div>

**Comment by Xaalek** [comment] 2022-06-10 22:42
@hahyes I can't reproduce the issue

![image](https://user-images.githubusercontent.com/54487782/173137028-a7b65d59-1665-4ab2-94d3-21395138e028.png)

Can you provide a test repo or something to be able to reproduce the problem please ?

**Comment by MichelMichels** [comment] 2022-11-08 19:32
@hahyes, I'll close this issue as there has been multiple months gone by with no answer. Feel free to reopen if you can provide us with more information regarding the problem.

**Closed by MichelMichels** 2022-11-08 19:32 UTC
Labels: bug, Waiting on feedback

**Comment by get-flat** [comment] 2024-01-10 10:32
Not sure if related but in my case it was simply `HeadersVisibility="All"` (which seems to be the default in WPF)

`  <Style x:Key="MaterialDesignDataGrid" TargetType="{x:Type DataGrid}">`
`      <Setter Property="HeadersVisibility" Value="Column" />`
