### ISSUE TITLE
pre-compiled demo 

### ISSUE THREAD

**Issue by JaychengLeo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3017] opened 2022-12-30 10:38 UTC
### Bug explanation

![image](https://user-images.githubusercontent.com/67141458/210060050-6977fe49-c453-47dc-a2d6-8d3801a3e7d6.png)
### Version

4.6.1

**Comment by nicolaihenriksen** [comment] 2022-12-30 13:52
@JaychengLeo closing this as it seems to be a duplicate of #2577. Please re-open if you disagree.

**Closed by nicolaihenriksen** 2022-12-30 13:52 UTC
Labels: bug, evaluation required
