### ISSUE TITLE
DialogHost and ComboBox don't disappear on breakpoint

### ISSUE THREAD

**Issue by qrzychu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1148] opened 2018-12-18 14:05 UTC
Hi, 

when I have  opened dialog or ComboBox and hit breakpoint, it stays on top of everything. I have a workaround - I move the window to second screen so I can see VS. However, sometimes I forget to do that, hit breakpoint very early or do something on a single screen, and then it is infuriating.

I have no idea if this is even possible to resolve, but I would be nice.

I've attached some screenshots of what it looks like.

![chrome](https://user-images.githubusercontent.com/4633810/50158992-d963d980-02d5-11e9-8423-3aec7e957cf9.PNG)

and after alt-tabbing from VS to Chrome:

![vs](https://user-images.githubusercontent.com/4633810/50158993-d963d980-02d5-11e9-9c7c-6483fcaca004.PNG)

**Comment by Tyrrrz** [comment] 2018-12-18 21:48
Yes, the root cause seems to be that the DialogHost somehow renders the dialog on top of all other windows.

Another way to reproduce this:
1. Have a button that shows dialog after a delay
```c#
public async void Button_Click(object sender, EventArgs args)
{
    await Task.Delay(3000);
    DialogHost.Show(new DialogWindow());
}
```
2. Click the button
3. Hide the window or open some other application's window so it becomes topmost
4. After the dialog is shown, it is shown over everything else, including other applications, while its own window is in fact not visible

**Comment by Tyrrrz** [comment] 2018-12-18 21:49
Also another funky way to reproduce (most likely) the same underlying issue:
1. Have a window with a dialog open
2. Click on the window's icon in the taskbar to hide the application
3. Dialog appears in the top left, is on top of other windows and doesn't hide until you re-open its window

**Comment by qrzychu** [comment] 2018-12-19 07:14
Another quick way is to put breakpoint in a property bound to `SelectedItem` of a combobox - same result

**Comment by qrzychu** [comment] 2018-12-19 11:36
I don't think you need to execute anything. Just disabling the TopMost should do the trick - allow other apps to be rendered on top.

**Comment by Tyrrrz** [comment] 2018-12-19 12:59
I agree, it seems the problem is not limited by breaking in debugger, but rather by how the dialog is rendered, as described above.

**Comment by Keboo** [comment] 2018-12-19 17:41
There is not really a way for this library to "fix" this. This is actually normal WPF behavior with popups. 
For example this occurs in a normal WPF project that is not using this library:
```XAML
<ComboBox DropDownOpened="ComboBox_OnDropDownOpened">
    <ComboBoxItem Content="1" />
    <ComboBoxItem Content="2" />
    <ComboBoxItem Content="3" />
</ComboBox>
```
```C#
private async void ComboBox_OnDropDownOpened(object sender, EventArgs e)
{
    //A little delay to let the popup animation run
    await Task.Delay(TimeSpan.FromSeconds(1));
    //Break point here after the delay
}
```

When the breakpoint is hit the combo box's dropdown is displayed on top of all other windows. This is because [Popups](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/popup-overview) 

> display content in a separate window that floats over the current application window

You will notice from the [docs](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/popup-overview#controls-that-implement-a-popup) that there are four built-in controls that implement a popup (ToolTip, ContextMenu, ComboBox, and Expander).
When using this library I will also add the controls DialogHost, PopupBox, anything using the popup validation template, and data grid text columns using the `MaterialDesignDataGridTextColumnPopupEditingStyle`. 

In the case of the DialogHost, there is an alternate style (`MaterialDesignEmbeddedDialogHost`) that does not use a popup and instead places the dialog inside of the visual tree of the window, rather than putting it in a popup. This does have the drawback of the dialog not being able to exceed the size of the parent window, but does work around the issue. As for the other controls, I am afraid there is not a great solution beyond simply moving the app to another screen while debugging.

Because this is not an issue with this library I am closing this. If anyone has suggestions on ways to address this please re-open.

**Closed by Keboo** 2018-12-19 17:41 UTC

**Comment by Tyrrrz** [comment] 2018-12-19 19:51
Oh, I didn't know `MaterialDesignEmbeddedDialogHost` existed. It solves the problems I was having.

**Comment by MuhammadSulaiman001** [comment] 2023-01-18 17:38
> I am afraid there is not a great solution beyond simply moving the app to another screen while debugging.

No, this is a great solution, I like it ❤️
