### ISSUE TITLE
Dialoghost.Show() may not work well in Drop event

### ISSUE THREAD

**Issue by wangsongpower** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3160] opened 2023-04-07 06:45 UTC
### Bug explanation

If showing a dialog in drop event, the dialog maybe disappear.

My program is to drag an image to window, then release, an error message shows up.
Those maybe happen below:
1. Sometimes, the dialog does not show up. but the overlap does. If left button click the overlap, the dialog shows. But if click the title bar, the dialog shows within 1s, and will not show up again.
2. For the same file (1.tif), the first time, the dialog does not show up, but then it shows up after the first time. If drag another file (2.tif), it will happen again, same as 1.tif.
3. (continue with 2.) Except "the first time", if click title bar, it is OK that dialog will not disappear.
4. For "the first time", if click and hold the tilte bar for a distance, the dialog will show up. but click the title bar, it will disappear and wont back.

My way of implementation:
- in mainwidonw
`<materialDesign:DialogHost Identifier="RootDialog"/>`
- navigation frame (page) in "materialDesign:DialogHost"
`<Frame x:Name="View_NavigationFrame" NavigationUIVisibility="Hidden" />`
- Dialoghost.Show() in viewmodel of page
`MessageBoxCustomize view;`
`await Dialoghost.Show(view, "RootDialog");`

Sorry for my poor English and bad writing layout.
Please check it.
If my implementation is bad, please tell me or just give me a link, thanks.
If need more info, please tell me.

Net 7.0, VS2022, WPF C#

### Version

4.8.0

**Comment by Keboo** [comment] 2023-04-08 05:12
Hi @wangsongpower are you able to provide a sample app that reproduces the behavior. It is difficult to say from the description above, but I suspect it will be related to the interaction between the `Frame` and the `DialogHost`.

**Comment by wangsongpower** [comment] 2023-04-08 06:07
> Hi @wangsongpower are you able to provide a sample app that reproduces the behavior. It is difficult to say from the description above, but I suspect it will be related to the interaction between the `Frame` and the `DialogHost`.

Thanks for the relay, please check this project.

I am a new C# (WPF) learner. I knew my coding is bad.
For example, I cant understand the example code of navigation in MDIX sample.
I did it in another simple way.
So I cant achieve the search function.
If you can give me some coding advice, will be appreciated

[TestForMDIX.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/11182643/TestForMDIX.zip)

**Comment by Keboo** [comment] 2023-04-08 06:24
Hi @wangsongpower thank you for the sample project. Because the dialog is shown as a popup, and since the popup is a separate window, in order to keep it from being on top of other applications, when your Window does not have focus the popup is hidden. This is the reason why clicking on the title bar makes it appear, because the window now has focus.
I have also written a [blog post on the dialog host](https://intellitect.com/blog/material-design-in-xaml-dialog-host/) you that might be helpful.

There are two possible solutions for you to consider.

Option 1: Manually give the window focus every time you show a dialog. You can do this by registering for the DialogOpened event.
In you `MainWindow.xaml` it would look like this:
```xaml
 <materialDesign:DialogHost DialogTheme="Inherit" Identifier="RootDialog" DialogOpened="DialogHost_DialogOpened">
```
The in your MainWindow.xaml.cs the event handler would look like this:
```c#
private void DialogHost_DialogOpened(object sender, MaterialDesignThemes.Wpf.DialogOpenedEventArgs eventArgs)
{
    Focus();
}
```

Option 2: The problem you are experiencing comes because the dialog is shown in a popup. The reason for the popup is to allow the dialog to be _larger_ than the parent window. If you would rather the dialog be part of window rather than live outside of it, you can use the alternate style "MaterialDesignEmbeddedDialogHost". This will have the limitation of your dialog not being able to be larger than the parent window (but in many app that is acceptable).
In your MainWindow.xaml you would do this:
```xaml
<materialDesign:DialogHost DialogTheme="Inherit" Identifier="RootDialog" Style="{StaticResource MaterialDesignEmbeddedDialogHost}">
```

**Comment by wangsongpower** [comment] 2023-04-09 01:40
Hello @Keboo , really thanks for your detailed comments.
I tried Option2, it works well.
As for 1, I didnt try. I guess it will happen again if click title bar.
And thanks for the blog link, I will check it now.
BR.

**Comment by wangsongpower** [comment] 2023-04-10 00:34
Hello @Keboo , sorry to bother you again.
I tried the option 1 today, would you mind giving me more comment?
For option 1, the dialog can show up, but if click the overlay or title bar, the dialog will disappear (behind the window in fact) again.
Is there any good way to prevent this?
Option 2 works well, but if the size of window is not large enough, some contents will be hidden.

Thanks

**Comment by Keboo** [comment] 2023-04-16 20:51
@wangsongpower after looking at your sample again, and poking at the code. Something I missed the first time was the Window was set as Topmost. I put in a PR to fix this case. It will be in tonight's nightly release. You should be able to pull the latest preview NuGet tomorrow to confirm it is fixed.

**Closed** 2023-04-16 21:04 UTC
Labels: question
