### ISSUE TITLE
Snackbar not disappearing

### ISSUE THREAD

**Issue by adhocmaster** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#724] opened 2017-06-04 06:22 UTC
Hi,

I am creating 3 snackbars with different speeds in the same place to show messages of different importance. So, a fast queue, a slow queue, and a normal queue. Problem is sometimes sometimes one of the snacbars do not close after showing the message. It just stays there and new messages added to its queue are not shown either. Other snackbars are working while its stuck.

Thanks,
Muktadir

**Comment by ButchersBoy** [comment] 2017-06-08 14:05
Please provide a full sample repo on GitHub.

**Comment by MalpenZibo** [comment] 2017-09-27 10:25
I have the same problem. If i have a dialog showed the snackbar message not disappear.
I have found that there is a infinite loop in DurationMonitor constructor on line 132, but when i set a breakpoint to inspect everything goes fine.

```csharp
private DurationMonitor(
    TimeSpan minimumDuration,
    WaitHandle pausedWaitHandle,
    EventWaitHandle signalWhenDurationPassedWaitHandle,
    WaitHandle ceaseWaitHandle)
{
    if (pausedWaitHandle == null) throw new ArgumentNullException(nameof(pausedWaitHandle));
    if (signalWhenDurationPassedWaitHandle == null)
        throw new ArgumentNullException(nameof(signalWhenDurationPassedWaitHandle));
    if (ceaseWaitHandle == null) throw new ArgumentNullException(nameof(ceaseWaitHandle));

    _completionTime = DateTime.Now.Add(minimumDuration);

    //this keeps the event waiting simpler, rather that actually watching play -> pause -> play -> pause etc
    var granularity = TimeSpan.FromMilliseconds(200);

    Console.WriteLine( "Pre task creation" );

    Task.Factory.StartNew(() =>
    {
        Console.WriteLine( "task created and running" );

        //keep upping the completion time in case it's paused...                
        while (DateTime.Now < _completionTime && !ceaseWaitHandle.WaitOne(granularity))
        {
            Console.WriteLine( "into the while" );

            if (pausedWaitHandle.WaitOne(TimeSpan.Zero))
            {
                Console.WriteLine( "inside if" );
                _completionTime = _completionTime.Add(granularity);
            }
        }

        Console.WriteLine( "loop ended" );
        if (DateTime.Now >= _completionTime)
        {
            signalWhenDurationPassedWaitHandle.Set();
        }
    });
}
```

Console output:
Pre task creation
task created and running
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
inside if
into the while
....... etc etc etc

**Comment by MalpenZibo** [comment] 2017-09-27 12:28
It's not a bug. 
When DialogHost.IsOpen is true the associated MessageQueue is paused. So all snackbar not disappear

**Comment by Keboo** [comment] 2019-09-23 05:39
Closing for now as it appears there is not enough information to accurately isolate the issue.

**Closed by Keboo** 2019-09-23 05:39 UTC
