### ISSUE TITLE
ColorPicker.Color TwoWay Binding returns wrong value if initial value was Black

### ISSUE THREAD

**Issue by HavenDV** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2813] opened 2022-08-11 15:52 UTC
### Bug explanation

I have the following code:
```xml
<material:ColorPicker
    Color="{Binding ViewModel.Color, Mode=TwoWay, Converter={StaticResource SystemDrawingColorToColorConverter}}"
    />
```
If the initial value was black, it cannot be changed. Any change from the UI to the converter will always return the initial black value.

### Version

4.5.0

**Comment by nicolaihenriksen** [comment] 2022-08-20 07:56
@HavenDV I have just tested this out in the Material Design In XAML demo app using a TwoWay binding, and there does not seem to be any issues. I can see that you are using an `IValueConverter` in your example, are you sure you have properly implemented both the `IValueConverter.Convert()` and `IValueConverter.ConvertBack()` methods?

**Comment by HavenDV** [comment] 2022-08-26 08:59
https://github.com/HavenDV/Uno.Issues/tree/main/material-ui-issue
<img width="470" alt="image" src="https://user-images.githubusercontent.com/3002068/186867730-ca093d31-4aef-4700-91fb-f7f57c33c748.png">
This works correctly by default, but if you change the base color to black, everything breaks.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/3002068/186867771-66c7a1ed-0c09-4029-ab44-2f79484538f2.png">

**Comment by nicolaihenriksen** [comment] 2022-08-26 09:20
> This works correctly by default, but if you change the base color to black, everything breaks.

@HavenDV Thank you for the sample, I will look into it when I have some free time.

**Comment by nicolaihenriksen** [comment] 2022-08-26 12:41
@HavenDV I briefly looked into the issue you're seeing. I don't actually think there is anything wrong with the values that are being set on your ViewModel. I think the confusion arises from some part of the control not being visible unless you give it an explicit size. By default, only the hue slider is visible, and that does not have an effect for certain colors (including black and white)

If you just add a `ColorPicker` it will look something like this. I have added a black 1px border just to show the outline of the control.
![image](https://user-images.githubusercontent.com/19572699/186904085-2f1071dd-214f-46c3-a967-6ed3262cfef5.png)

However, if you on set an explicit size on the control, in this case a height of 100px, it becomes evident what the issue is.
![image](https://user-images.githubusercontent.com/19572699/186904075-d5c1c739-24c7-4034-82d4-9541502ca754.png)

So by simple dragging the hue slider, you're not effectively changing the color which it converts to.

The `ColorPicker` has a dependency property `HueSliderPosition` which effectively lets you move the positioning of the hue slider around the edges of the "color selection" part. Please excuse my color space lingo, I am most likely not using the correct terms.

All in all, I don't think there is a bug around the dependency property updates as such, but perhaps a default `MinWidth`/`MinHeight` of the color selection could be set such to avoid confusion? There may be use cases where the hue slider is sufficient for some user, but I really don't know. @Keboo Thoughts?

**Comment by HavenDV** [comment] 2022-08-26 12:55
Thanks, I didn't know that this control has another mode. But, perhaps, for a mode without an explicit height, it is worth using the color from the slider? Because in this mode, the user will not be able to change the color if an incorrect initial color is specified for some reason.

**Comment by nicolaihenriksen** [comment] 2022-08-26 13:24
> Thanks, I didn't know that this control has another mode. But, perhaps, for a mode without an explicit height, it is worth using the color from the slider? Because in this mode, the user will not be able to change the color if an incorrect initial color is specified for some reason.

I understand your frustration, but I don't think this control was built for a scenario like that. As mentioned, the slider simply controls the hue, and if the "base color" is black, then changing the hue has no effect. You will also notice that the slider does not include black/white, so it would not be useful on its own; at least it will not let the user freely select a color (or shades of a certain color). It is not really a "mode", but perhaps the `ColorPicker` simply has an desirable default size which hides a pretty important part of the control.

I think for something like this, it has to be a 2-step process to pick the desired color. An alternative you could use is to display a set of pre-calculated colors to pick from (the demo application has examples of this I believe).

**Comment by HavenDV** [comment] 2022-08-26 13:46
Thank you for your time on this issue and for your tips. Now, understanding the problem, it is not difficult to solve it.
Another idea - the second part of the control can be pop-up, appearing when changing

**Comment by nicolaihenriksen** [comment] 2022-09-23 20:08
@HavenDV Would you be ok with closing this issue based on the above discussion? Your last comment is probably more of a feature request than a bug/issue.

**Closed** 2022-09-27 03:50 UTC
Labels: bug

**Comment by HavenDV** [comment] 2022-09-27 03:52
Thanks for your time for this problem. Yes, I should close it. I'm currently in the process of relocating, sorry for the delay
