### ISSUE TITLE
Text looks bad inside Flipper.

### ISSUE THREAD

**Issue by saklanmaz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2582] opened 2022-02-17 08:49 UTC
Hello,

The texts and border of the button used in Flipper are dim. I've included my sample code and image below.

I'm using version 4.1.0

First Button -> Normally Button

Second Button -> Flipper

![Ekran Alıntısı](https://user-images.githubusercontent.com/96776256/154441539-4d37ada2-362c-49a8-8717-0ebada9801e1.PNG)

```
<StackPanel Orientation="Horizontal" Margin="0,10,0,0">
                                <Button Style="{StaticResource MaterialDesignOutlinedButton}"
                                        Content="TEST RUN"  
                                        Width="175"/>

                                <materialDesign:Flipper Margin="10,0,0,0">
                                    <materialDesign:Flipper.FrontContent>
                                        <Button Style="{StaticResource MaterialDesignOutlinedButton}"
                                                Command="{x:Static materialDesign:Flipper.FlipCommand}"
                                                Width="175"
                                                BorderThickness="1"
                                                Content="TEST RUN" />
                                    </materialDesign:Flipper.FrontContent>
                                    <materialDesign:Flipper.BackContent>
                                        <Button Style="{StaticResource MaterialDesignOutlinedButton}"
                                                Command="{x:Static materialDesign:Flipper.FlipCommand}"
                                                Width="175"
                                                Content="TEST STOP" />
                                    </materialDesign:Flipper.BackContent>
                                </materialDesign:Flipper>
                            </StackPanel>
```

**Comment by nicolaihenriksen** [comment] 2024-10-09 11:35
Closing as a duplicate of #3220

**Closed by nicolaihenriksen** 2024-10-09 11:35 UTC
Labels: bug
