### ISSUE TITLE
System.Windows.Markup.XamlParseException: 

### ISSUE THREAD

**Issue by sergioPerez-e** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1156] opened 2018-12-26 06:37 UTC
#System.Windows.Markup.XamlParseException: 

## After edit App.axml, i see:

**''La invocación del constructor del tipo 'Deportes_WPF.Login' que coincide con las restricciones de enlace especificadas produjo una excepción.' (número de línea: '5'; posición de línea: '9').'"**

My App.xml:

```
<Application x:Class="Deportes_WPF.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="Vista/Login.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

```

Thanks for your attention.

**Comment by jespersh** [comment] 2018-12-26 09:46
Your constructor of Deportes_WPF.Login threw an exception. Check there

**Comment by Keboo** [comment] 2018-12-27 16:06
@sergioPerez-e the issue is in your `Deportes_WPF.Login` window. Can you share that code as well?

**Comment by sergioPerez-e** [comment] 2018-12-27 18:36
Of cuorse. Thanks for your time.

The source code is here: https://github.com/GonzalezPerezCO/Alpha-Sport-Desktop

**Comment by Keboo** [comment] 2021-09-24 16:52
Closing for now as it appears outside of this library

**Closed by Keboo** 2021-09-24 16:52 UTC
Labels: question
