### ISSUE TITLE
version 2.6.0  The value "MaterialDesignThemes.Wpf.CustomColorTheme" is not of type "System.Windows.ResourceDictionary"

### ISSUE THREAD

**Issue by tomasfil** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1352] opened 2019-08-06 10:50 UTC
`
<Application x:Class="DR_SORES.App"  StartupUri="Authenticate_Window.xaml"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:CustomColorTheme BaseTheme="Light" Primary="Aqua" Secondary="DarkGreen" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

is throwing 

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		The value "MaterialDesignThemes.Wpf.CustomColorTheme" is not of type "System.Windows.ResourceDictionary" and cannot be used in this generic collection.
Parameter name: value	DR_SORES	App.xaml	8	IntelliSense	

I have installed version 2.6.0. Same issue with .net 4.5.2 and 4.6.1, well, with every version.

**Comment by Keboo** [comment] 2019-08-06 17:33
That is a markup extension that returns a resource dictionary.

Can you provide a sample project that reproduces the issue?

**Comment by tomasfil** [comment] 2019-08-07 07:39
Hello,
I was just following the Get started guide. As it seems, I am not the only one with the problem.
(eg. gitter chat https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit#)

There is sample project:
https://drive.google.com/file/d/1HI1ICHxjt9rB3PA9kNvRLlesFuTbbmRb/view?usp=sharing

All I did was installing nuget package and adding markup from getting started to app.xaml.

In app.xaml error:

```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		The value "MaterialDesignThemes.Wpf.BundledTheme" is not of type "System.Windows.ResourceDictionary" and cannot be used in this generic collection.
Parameter name: value	MatDesignError	App.xaml	10	IntelliSense	

```

**Comment by Keboo** [comment] 2019-08-07 18:17
One final question what version of visual studio are you running (Help>>About Microsoft Visual Studio)? I am currently on Visual Studio 2019 version 16.1.4

I am not able to reproduce this one my environment, but I am noticing a couple of thing.
1. This is an intellisense error not actually a run-time issue. Correct me if I am wrong, but I suspect your app should launch and work correctly.
2. I also have ReSharper installed which I know affects the intellisense. Are you running any tools like this?

**Comment by Awsmolak** [comment] 2019-08-07 21:57
I am having the same problem with pulling "materialDesign:CustomColorThem" in my project. It 

I have also opened the source solution and I am getting the same problem in MainDemo/App.xaml when I comment in line 23:
`<materialDesign:CustomColorTheme BaseTheme="Light" Primary="Aqua" Secondary="DarkGreen" />`

I am on VisualStudio 2019 v16.1.4 no resharper.

This is not a problem during runtime. But it results in design time being unusable because resources cannot be located. Example designer error: "Cannot find resource named 'MaterialDesignLightForeground'. Resource names are case sensitive."

**Comment by Awsmolak** [comment] 2019-08-07 22:22
I have also tested the same code in VS 2017 with ReSharper installed and I am getting the same errors.

**Comment by Awsmolak** [comment] 2019-08-08 01:19
After working on this for a bit I'm starting to think that it's not actually possible to provide a resource dictionary this way during design time!

Instead you need to provide an implementation of ResourceDictionary that has a parameterless constructor. It's kind of hackey, but because you can't pass parameters in WPF XAML, you can set the theme in the setter of the properties. Here is what I came up with as a replacement for CustomColorTheme. I can make a cleaner implementation and push a branch if you would like tomorrow.

`public class CustomColorTheme2 : ResourceDictionary
    {
        private BaseTheme _baseTheme;
        public BaseTheme BaseTheme
        {
            get { return _baseTheme; }
            set
            {
                _baseTheme = value;
            }
        }

        private Color _primary;
        public Color Primary
        {
            get { return _primary; }
            set
            {
                _primary = value;
            }
        }

        private Color _secondary;
        public Color Secondary
        {
            get { return _secondary; }
            set
            {
                _secondary = value;
                SetTheme(GetTheme(), this);
            }
        }

        protected ITheme GetTheme()
        {
            return Theme.Create(BaseTheme.GetBaseTheme(), Primary, Secondary);
        }

        protected virtual void SetTheme(ITheme theme, ResourceDictionary resourceDictionary)
        {
            resourceDictionary.SetTheme(theme);
        }

        public CustomColorTheme2()
        {
        }
    }`

**Comment by tomasfil** [comment] 2019-08-08 07:54
> One final question what version of visual studio are you running (Help>>About Microsoft Visual Studio)? I am currently on Visual Studio 2019 version 16.1.4
> 
> I am not able to reproduce this one my environment, but I am noticing a couple of thing.
> 
> 1. This is an intellisense error not actually a run-time issue. Correct me if I am wrong, but I suspect your app should launch and work correctly.
> 2. I also have ReSharper installed which I know affects the intellisense. Are you running any tools like this?

I am on visual studio 2017 no resharper. Program debugs and runs, but as @Awsmolak wrote, I am having same issues "Cannot find resource named ..." 
I am using 
`
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Teal.xaml" />
` for now, till it gets fixed

**Comment by Awsmolak** [comment] 2019-08-08 18:26
@tomasfil  I made a fix and also merged in another fix. Everything seems to be working well in design mode with my custom colors.

Until the updates are pushed and released on NuGet you can download and build this branch to get up and running:
https://github.com/Awsmolak/MaterialDesignInXamlToolkit/tree/mergeFix1327andFix1357

**Comment by Miosss** [comment] 2019-08-12 11:30
VS 2019, no ReSharper, same issue.
Just after installing I get the error:
```
MaterialDesignThemes.Wpf.CustomColorTheme" is not of type "System.Windows.ResourceDictionary" and cannot be used in this generic collection.
```

Which is probably responsible for the following errors in xaml designer:
```
The resource "MaterialDesignBody" could not be resolved.
```
etc.

The app itself build and runs just fine.

**Closed** 2019-09-10 15:12 UTC
Labels: bug

**Comment by Taschenbuch** [comment] 2019-09-20 20:13
Is the fix already included in the nuget package? If yes, than it is not fixed yet. I just added the nuget packet and used the code from the quickstart guide. And I got the problem mentioned here.

This quickstart guide:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started

**Comment by Keboo** [comment] 2019-09-20 20:20
@Taschenbuch which version of the NuGet package are you using?

**Comment by Taschenbuch** [comment] 2019-09-20 20:25
@Keboo 
MaterialDesignThemes 2.6.0
MaterialDesignColors 1.2.0

**Comment by Keboo** [comment] 2019-09-20 20:27
@Taschenbuch ah I see the problem I forgot to move this issue into the 3.0.0 milestone. The fix for this is going out in the next release. You can also download the preview 3.0.0 NuGet packages if you need the fix right away.
