### ISSUE TITLE
Bug in the style MaterialDesignExpander

### ISSUE THREAD

**Issue by ambyte** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#341] opened 2016-04-15 12:49 UTC
Hi,

After [this ](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/commit/056cf9d467a0b8bebdd0832f83fc5e51f5cf61a1?diff=split) commit I have a bug when use an expander control in grouped listbox.

Exception thrown: 'System.ArgumentNullException' in PresentationCore.dll
System.ArgumentNullException: Value cannot be null.
Parameter name: defaultOriginValue
   in System.Windows.Media.Animation.DoubleAnimationBase.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue, AnimationClock animationClock)
   in System.Windows.Media.Animation.AnimationStorage.GetCurrentPropertyValue(AnimationStorage storage, DependencyObject d, DependencyProperty dp, PropertyMetadata metadata, Object baseValue)
   in System.Windows.Media.Animation.AnimationStorage.EvaluateAnimatedValue(PropertyMetadata metadata, EffectiveValueEntry& entry)
   in System.Windows.UIElement.EvaluateAnimatedValueCore(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& entry)
   in System.Windows.DependencyObject.EvaluateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry newEntry, OperationType operationType)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   in System.Windows.StyleHelper.InvalidatePropertiesOnTemplateNode(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, Boolean isDetach, FrameworkElementFactory templateRoot)
   in System.Windows.StyleHelper.ClearTemplateChain(HybridDictionary[] instanceData, FrameworkElement feContainer, FrameworkContentElement fceContainer, List`1 templateChain, FrameworkTemplate oldFrameworkTemplate)
   in System.Windows.StyleHelper.ClearGeneratedSubTree(HybridDictionary[] instanceData, FrameworkElement feContainer, FrameworkContentElement fceContainer, FrameworkTemplate oldFrameworkTemplate)
   in System.Windows.StyleHelper.DoTemplateInvalidations(FrameworkElement feContainer, FrameworkTemplate oldFrameworkTemplate)
   in System.Windows.Controls.Control.OnTemplateChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   in System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   in System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   in System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   in System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   in System.Windows.FrameworkElement.UpdateStyleProperty()
   in System.Windows.TreeWalkHelper.InvalidateStyleAndReferences(DependencyObject d, ResourcesChangeInfo info, Boolean containsTypeOfKey)
   in System.Windows.TreeWalkHelper.OnResourcesChanged(DependencyObject d, ResourcesChangeInfo info, Boolean raiseResourceChangedEvent)
   in System.Windows.FrameworkElement.OnAncestorChangedInternal(TreeChangeInfo parentTreeState)
   in System.Windows.TreeWalkHelper.OnAncestorChanged(DependencyObject d, TreeChangeInfo info, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   in MS.Internal.PrePostDescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   in System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
   in System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)
   in System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   in System.Windows.Media.Visual.RemoveVisualChild(Visual child)
   in System.Windows.Media.VisualCollection.DisconnectChild(Int32 index)
   in System.Windows.Media.VisualCollection.Clear()
   in System.Windows.Controls.UIElementCollection.ClearInternal()
   in System.Windows.Controls.Panel.ClearChildren()
   in System.Windows.Controls.Panel.EnsureEmptyChildren(FrameworkElement logicalParent)
   in System.Windows.Controls.Panel.OnItemsChangedInternal(Object sender, ItemsChangedEventArgs args)
   in System.Windows.Controls.Panel.OnItemsChanged(Object sender, ItemsChangedEventArgs args)
   in System.Windows.Controls.ItemContainerGenerator.OnRefresh()
   in System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   in System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   in System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   in System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   in System.Collections.ObjectModel.ReadOnlyObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   in System.Collections.ObjectModel.ReadOnlyObservableCollection`1.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   in System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   in System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   in System.Collections.ObjectModel.Collection`1.Clear()
   in MS.Internal.Data.CollectionViewGroupInternal.Clear()
   in System.Windows.Data.ListCollectionView.PrepareShaping()
   in System.Windows.Data.ListCollectionView.PrepareLocalArray()
   in System.Windows.Data.ListCollectionView.RefreshOverride()
   in System.Windows.Data.CollectionView.RefreshInternal()
   in System.Windows.Data.CollectionView.Refresh()

In the attached sample project reproduced this bug.
[ListBoxGrouping.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/220964/ListBoxGrouping.zip)
Sample have a grouped listbox, for get an error need check or uncheck all items

The problem in the style MaterialDesignExpander for an expander control, lines
`<DoubleAnimation Storyboard.TargetProperty="Tag" Storyboard.TargetName="ContentPanel" To="1" Duration="0"/>`
and
`<DoubleAnimation Storyboard.TargetProperty="Tag" Storyboard.TargetName="ContentPanel" To="0" Duration="0"/>`
if comment this lines an error disappear.

**Comment by mgnslndh** [comment] 2016-04-19 14:21
Perhaps @l1pton17, the author of 056cf9d467a0b8bebdd0832f83fc5e51f5cf61a1 can have a look at this?

**Comment by l1pton17** [comment] 2016-04-19 15:50
@mgnslndh perhaps :smile:

**Comment by l1pton17** [comment] 2016-04-27 23:05
@ambyte hi, i've tried to reproduce this bug but can't. I used the Expander style from materialdesign lib. Can you try your example with Expander style from materialdesign lib?
![ex](https://cloud.githubusercontent.com/assets/5460448/14870785/5e1d0898-0ce5-11e6-977f-09f6650ad39f.gif)

**Comment by ambyte** [comment] 2016-04-28 10:25
@l1pton17 hi,
Yes, if insert ResourceDictionary in the App.xaml all works fine. But if insert it in the window.xaml an error will occur. I think it should not be.

**Comment by hanvyj** [comment] 2016-06-25 11:08
I've got the same issue, adding the style into App.xaml doesn't seem to fix it...

**Comment by grossmann** [comment] 2016-07-27 09:37
Same issue here but it happens in the designer window. You can even user the MaterialDesignDemo as an example. Just open Expander.xaml and activate design view. The Exception is shown as seen below.
![vsdesignerexception](https://cloud.githubusercontent.com/assets/1866724/17170876/5de5155a-53ee-11e6-91f7-a44d1297eb58.PNG)
Commenting all lines with `Storyboard.TargetProperty="Tag"` seems to fix this.

**Comment by dastrn** [comment] 2016-11-23 02:51
I'm able to reproduce this by simply using an Expander with anything from the material design namespace inside.

**Comment by ButchersBoy** [comment] 2016-11-23 08:36
@dastrn I don't have this issue...can you post a sample repo?

**Comment by Erik8309** [comment] 2016-11-28 08:25
Im also getting the same exception when using a grouped expander, but I use it in a WPF Datagrid. 
The exception is thrown when trying to clear GroupDescriptions.
I created a post at stackoverflow about this (didnt know it was related to Material Design at that time):
http://stackoverflow.com/questions/40679953/listcollectionview-groupdescriptions-clear-throws-argumentnullexception

**Comment by ButchersBoy** [comment] 2016-11-28 08:35
@Erik8309 Can you post a sample repo on GitHub?

**Comment by Erik8309** [comment] 2016-11-29 10:44
@ButchersBoy, I've done even better, I've found whats causing the problem (for me):
Im calling the WPF application with Material Design from a class library and to do all the stuff that App.xaml does I've created a ResourceDictionary that holds what App.xaml should hold and I just reference that like this:

`    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Resources.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>`

And I also reference the ResourceDictionary in the MainWindow.xaml. 

`        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Resources.xaml"/>
            </ResourceDictionary.MergedDictionaries>
                    </ResourceDictionary>`

If I remove the ResourceDictionary from MainWindow.xaml and do it instead in App.xaml it works.
The "hack" described here:
http://www.carlosjanderson.com/beautify-your-wpf-apps-with-material-design/

I have no idea about whats going on under the hood, but there is it. 

If I remove the ResourceDictionary fromt the MainWindow.xaml I can´t show the dialog =/
Any ideas?

**Comment by Erik8309** [comment] 2016-12-02 13:31
After some researching, I could move away from using the method described above and I only use App.xaml when I call my WPF applications from class libraries. This seems to be a more correct way of doing it and it works.

**Comment by Keboo** [comment] 2018-08-17 05:52
Hi @dastrn and @Erik8309 I realize this issue is pretty old at this point. Are you still facing this problem? Can you attempt re-testing with the latest 2.5.0 preview nugets and let me know if this is still and issue? 

Thanks

**Comment by Keboo** [comment] 2019-01-21 08:16
Closing for now due to inactivity. If there is still an issue please re-open with details.

**Closed by Keboo** 2019-01-21 08:16 UTC
Labels: details needed
