### ISSUE TITLE
PopupBox with Style MaterialDesignMultiFloatingActionAccentPopupBox on startup hides sub-elements but leaves them active

### ISSUE THREAD

**Issue by scual** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#723] opened 2017-06-01 17:02 UTC
Just a quick report:
I've tried this one also on the demo application and it's reproduced there as well.

It seems like that when a PopupBox is first created, its sub-elements are not rendered - however they are active (i.e. if we are talking about a stackpanel of buttons, those will be clickable even if not visible).
This issues kind of solves itself as soon as the PopupBox is used for the first time.

I'll just flag the issue, but won't go too deep into it as not having time ATM, but I'll show a small workaround that can be made while the issue is solved.

If we take the code from the wpf demo project:
```
<materialDesign:PopupBox Style="{StaticResource MaterialDesignMultiFloatingActionAccentPopupBox}"
                                     PlacementMode="BottomAndAlignCentres"                                                                      
                                     ToggleCheckedContentCommand="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType=wpfExample:Buttons}, Path=FloatingActionDemoCommand}"
                                     ToggleCheckedContentCommandParameter="wowsers"
                                     Margin="0 0 48 0"
                                     ToolTip="PopupBox, Style MaterialDesignMultiFloatingActionAccentPopupBox">
                    <materialDesign:PopupBox.ToggleCheckedContent>
                        <materialDesign:PackIcon Kind="Pencil" Width="24" Height="24" />
                    </materialDesign:PopupBox.ToggleCheckedContent>
                    <StackPanel>
                        <Button ToolTip="One">1</Button>
                        <Button ToolTip="Two" IsEnabled="False">2</Button>
                        <Button ToolTip="Three">3</Button>
                    </StackPanel>
                </materialDesign:PopupBox>
```

If we ran the code above we will have the following happening: the button One is active and clickable even though not visible (now the mouse arrow is missing from the screen-shot, but the tooltip is still visible),

<img width="145" alt="untitled" src="https://cloud.githubusercontent.com/assets/6215286/26690681/22e76cee-46f2-11e7-9e3d-3ca17d0d6ea1.png">

As I said I didn't have a good look to the source code, so I can't really tell where the fix should be, however a quick workaround is possible: given a user-defined BoolToVisibibility converter, this can be applied to the PopupBox container in order to hide it when the property IsPopupOpen is false:

```
<!-- add the name to the popupBox -->
<materialDesign:PopupBox Name="MyPopupBox" Style="{StaticResource MaterialDesignMultiFloatingActionAccentPopupBox}"
                                     PlacementMode="BottomAndAlignCentres"                                                                      
                                     ToggleCheckedContentCommand="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType=wpfExample:Buttons}, Path=FloatingActionDemoCommand}"
                                     ToggleCheckedContentCommandParameter="wowsers"
                                     Margin="0 0 48 0"
                                     ToolTip="PopupBox, Style MaterialDesignMultiFloatingActionAccentPopupBox">
                    <materialDesign:PopupBox.ToggleCheckedContent>
                        <materialDesign:PackIcon Kind="Pencil" Width="24" Height="24" />
                    </materialDesign:PopupBox.ToggleCheckedContent>
<!-- add the visibility binding -->
                    <StackPanel Visibility="{Binding Path=IsPopupOpen, ElementName=MyPopupBox, Converter={StaticResource BoolToVisibilityConverter}}">
                        <Button ToolTip="One">1</Button>
                        <Button ToolTip="Two" IsEnabled="False">2</Button>
                        <Button ToolTip="Three">3</Button>
                    </StackPanel>
                </materialDesign:PopupBox>

```

Hope this helps -

**Comment by Insire** [comment] 2017-06-01 17:05
Interesting workaround. I encountered the same problem here #504

**Comment by scual** [comment] 2017-06-01 17:07
Oh did see the #504 - otherwise I would have posted there. Sorry

**Comment by krisztianmukli** [comment] 2020-07-03 06:17
There are any progress this bug? scual's workaround doesn't work for me, but the problem is disappeared when I change the PopupMode to Click. (But this way changed the behaviour of the popupbox).

**Comment by MichelMichels** [comment] 2024-04-01 10:29
Reported as fixed by JCL on Discord: 
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/6505319/132fd54c-2003-4a6a-917d-f1a0c9978426)

**Closed by MichelMichels** 2024-04-01 10:29 UTC
Labels: bug
