### ISSUE TITLE
Crash on ShadowAssist when animating dropShadoweffect

### ISSUE THREAD

**Issue by Hadramet** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3064] opened 2023-01-26 11:21 UTC
### Bug explanation

The crash occurs in the DarkenPropertyChangedCallback function and the error message is an InvalidOperationException that says "Cannot animate the 'Opacity' property on DropShadoweffect."

**Steps to reproduce:**

1. Launch MaterialDesign3Demo/Demo app
2. Change theme color mode to Dark Mode
3. Go to color tools page or Dialog page

**Expected behavior:**
The animation of the dropShadoweffect's `Opacity `property should occur without any issues or errors.

**Actual behavior:**
The application crashes and an `InvalidOperationException` is thrown with the message "Cannot animate the 'Opacity' property on `DropShadoweffect`."
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/bc949be1847c1a16e57d93a37fb9b88bb79da75a/MaterialDesignThemes.Wpf/ShadowAssist.cs#L52 

**Environment:**

MaterialDesignToolKit : (Branch 5.0.0)
Operating System: Windows11 v22H2 , OSBUILD 22621.1105
.NET  version on launch: net7.0-windows

Thanks for your help,
Hadramet

![image](https://user-images.githubusercontent.com/12943293/214822515-932151fa-9e64-46fa-bbca-1c517d55296e.png)

### Version

5.0.0

**Comment by nicolaihenriksen** [comment] 2023-01-29 10:53
Alternative repro steps:

**Steps to reproduce**

1. Start up MaterialDesign3 demo app
2. Move the mouse over the "green github button"

![Crash](https://user-images.githubusercontent.com/19572699/215321241-80f246cf-d95b-40be-b817-4d20be655776.gif)

**Comment by nicolaihenriksen** [comment] 2023-01-29 10:56
@Keboo I suspect commit bc949be1847c1a16e57d93a37fb9b88bb79da75a is the root cause where you decided to freeze the `DropShadowEffect` in the `ShadowConverter`.

**Comment by Keboo** [comment] 2023-01-30 08:05
Good catch. Pushed the fix to the 5.0.0 branch.

**Closed** 2023-01-30 08:05 UTC
Labels: bug
