### ISSUE TITLE
Visual Tree stuck at DialogHost

### ISSUE THREAD

**Issue by tama10111** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1641] opened 2020-02-04 09:07 UTC
Hi !

I'm trying to use DialogHost. Unfortunatelly, the visual tree get stuck at it, so my MainWindow content is blank.

Here is a part of my XAML (IsOpen is set to True but it was a test, I tried without): 

![Capture](https://user-images.githubusercontent.com/14976249/73729672-c6a8a000-4735-11ea-9622-6b3939bcb318.PNG)

This is my MainWindow.xaml. I'm binding its DataContext with my MainWindowViewModel which is just interacting with the DrawerHost.Content (A ScrollViewer that hosts Controls). 

I haven't added any logic with the dialog host for now.
I tried with and without DialogContent.

Here is the visual tree with DialogHost Properties

![Capture](https://user-images.githubusercontent.com/14976249/73729714-dcb66080-4735-11ea-8f7c-339b219ef3c2.PNG)

I'll provide you what you want to help you

Thanks you

**Comment by jespersh** [comment] 2020-02-04 11:35
This was fixed in maybe 2.5 or not until 3.0, but I did see it in 2.4
What is your nuget package version?

**Comment by tama10111** [comment] 2020-02-04 12:30
My current version is 3.0.1.920

**Comment by Keboo** [comment] 2020-02-04 18:01
Looks like it might be a regression.

**Comment by jespersh** [comment] 2020-02-05 08:08
I'm also on 3.0.1 and I see it in my visual tree. 
![image](https://user-images.githubusercontent.com/1004198/73822607-c15f5a00-47f6-11ea-9986-8366935703d7.png)

I currently target Core 3.0, there is a newer 3.1.
My Visual Studio is Version 16.4.2, there is a newer 16.4.4.
Is any of those two different in your case?

**Comment by tama10111** [comment] 2020-02-05 09:11
Both haha, my Visual Studio version is 16.4.4 and my .NET core version is 3.1.101

**Comment by jespersh** [comment] 2020-02-05 10:06
I'll try to update to 16.4.4 later today/tomorrow and see if it makes a difference.

**Comment by jespersh** [comment] 2020-02-05 10:52
Updated to 16.4.4 and I still see it in the Visual tree.
Wondering if it has to do with 3.1 then?

**Comment by tama10111** [comment] 2020-02-05 12:50
How can I share it ?

More informations : Because I can't share you the sources of my projet, I created a test project. Using the default WPF project pattern provided by Visual Studio, I added the NuGet packages MaterialDesignThemes (3.0.1.920) and MaterialDesignColors (1.2.2.920), Runtime version : v4.0.30319

Here are the libraries used : 
![Capture](https://user-images.githubusercontent.com/14976249/73842926-df8c8080-481d-11ea-8db9-dc398cc864a4.PNG)

All versions for Presentation*, System*, WindowsBase and Microsoft.CSharp are 4.0.0.0

Still the same problem :
![Capture](https://user-images.githubusercontent.com/14976249/73843038-1b274a80-481e-11ea-83ed-91066a1df320.PNG)

**Comment by jespersh** [comment] 2020-02-05 13:26
Create a repo here https://github.com/new and push the code and share the link with your test project

**Comment by tama10111** [comment] 2020-02-05 13:53
Forgot that we were on Github... I'll share it to you in several hours, can't use GitHub on Visual Studio or on desktop behind my corporate proxy

**Comment by tama10111** [comment] 2020-02-05 20:46
Here is the link : https://github.com/tama10111/DialogHostBugApp/tree/master/DialogHostBugApp

**Comment by jespersh** [comment] 2020-02-06 06:56
> Here is the link : [tama10111/DialogHostBugApp:DialogHostBugApp@`master`](https://github.com/tama10111/DialogHostBugApp/tree/master/DialogHostBugApp) [](/tama10111/DialogHostBugApp/tree/HEAD@{2020-02-05T20:46:55Z}/DialogHostBugApp)

You haven't added the resources in: https://github.com/tama10111/DialogHostBugApp/blob/master/DialogHostBugApp/App.xaml
Follow this guide:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start

**Comment by tama10111** [comment] 2020-02-06 08:44
Ok, in my real project, I didn't added MaterialDesignTheme.Defaults.xaml as a resource dictionary, here was the mistake. Now it works, thanks !

**Closed** 2020-02-06 09:04 UTC
Labels: bug
