### ISSUE TITLE
ArgumentNullException in DialogClosingEventArgs

### ISSUE THREAD

**Issue by yexcoffier** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1328] opened 2019-07-19 12:56 UTC
I'm sorry but I can't really tell what happened, I just picked up this crash in our logs :

```
Fatal	EXCEPTION	System.ArgumentNullException: Value cannot be null.
Parameter name: session
   at MaterialDesignThemes.Wpf.DialogClosingEventArgs..ctor(DialogSession session, Object parameter, RoutedEvent routedEvent) in C:\projects\materialdesigninxamltoolkit\MaterialDesignThemes.Wpf\DialogClosingEventArgs.cs:line 18
   at MaterialDesignThemes.Wpf.DialogHost.Close(Object parameter) in C:\projects\materialdesigninxamltoolkit\MaterialDesignThemes.Wpf\DialogHost.cs:line 573
   at MaterialDesignThemes.Wpf.DialogHost.ContentCoverGridOnMouseLeftButtonUp(Object sender, MouseButtonEventArgs mouseButtonEventArgs) in C:\projects\materialdesigninxamltoolkit\MaterialDesignThemes.Wpf\DialogHost.cs:line 625
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToMouse(StagingAreaInputItem stagingItem)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainUpToTouch(WispStylusDevice stylusDevice, StagingAreaInputItem stagingItem)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToTouch(ProcessInputEventArgs e, StylusEventArgs stylusEventArgs)
   at System.Windows.Input.StylusWisp.WispLogic.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.StylusWisp.WispLogic.InputManagerProcessInput(Object oInput)
   at System.Windows.Input.StylusWisp.WispLogic.PreProcessInput(Object sender, PreProcessInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
```

All I can tell is that I'm using MaterialDesignThemes 2.5.0.1205, 
project is on .Net 4.7.2
DialogHost.Style is MaterialDesignEmbeddedDialogHost

The interface is used on a touch screen.

**Comment by Keboo** [comment] 2019-07-19 16:13
@yexcoffier that looks like a bug. Can you provide any more details or reproduction steps on how to trigger this error case?

**Comment by yexcoffier** [comment] 2019-07-22 08:58
I was able to reproduce it :
Xaml :
```xaml
<Window x:Class="TestDialogHost.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:local="clr-namespace:TestDialogHost"
        xmlns:material="http://materialdesigninxaml.net/winfx/xaml/themes"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="MainWindow"
        Width="800"
        Height="450"
        Loaded="Window_Loaded"
        mc:Ignorable="d">
    <Grid Background="Black">
        <material:DialogHost CloseOnClickAway="True"
                             IsOpen="{Binding RelativeSource={RelativeSource AncestorType=local:MainWindow}, Path=IsDialogOpen}"
                             Style="{DynamicResource MaterialDesignEmbeddedDialogHost}">
            <material:DialogHost.DialogContent>
                <Rectangle Width="100"
                           Height="100"
                           Fill="Yellow" />
            </material:DialogHost.DialogContent>
        </material:DialogHost>
    </Grid>
</Window>
```

Code behind C# :
```C#
public partial class MainWindow : Window
{
    [System.Runtime.InteropServices.DllImport("user32.dll")]
    static extern bool SetCursorPos(int x, int y);

    [System.Runtime.InteropServices.DllImport("user32.dll")]
    public static extern void mouse_event(int dwFlags, int dx, int dy, int cButtons, int dwExtraInfo);

    public const int MOUSEEVENTF_LEFTDOWN = 0x02;
    public const int MOUSEEVENTF_LEFTUP = 0x04;

    public bool IsDialogOpen
    {
        get { return (bool)GetValue(IsDialogOpenProperty); }
        set { SetValue(IsDialogOpenProperty, value); }
    }
    public static readonly DependencyProperty IsDialogOpenProperty =
        DependencyProperty.Register("IsDialogOpen", typeof(bool), typeof(MainWindow), new PropertyMetadata(false));


    public MainWindow()
    {
        InitializeComponent();
    }

    private void Window_Loaded(object sender, RoutedEventArgs e)
    {
        Task.Run(async () =>
        {
            for (int i = 0; i < 10000; i++)
            {
                await Task.Delay(500);
                Dispatcher.Invoke(() => IsDialogOpen = !IsDialogOpen);
            }
        });

        Task.Run(async () =>
        {
            for (int i = 0; i < 1000; i++)
            {
                await Task.Delay(600);

                var posOnScreen = await Dispatcher.InvokeAsync(() => this.PointToScreen(new Point(10, 10)));

                SetCursorPos((int)posOnScreen.X, (int)posOnScreen.Y);
                mouse_event(MOUSEEVENTF_LEFTDOWN, (int)posOnScreen.X, (int)posOnScreen.Y, 0, 0);
                await Task.Delay(5);
                mouse_event(MOUSEEVENTF_LEFTUP, (int)posOnScreen.X, (int)posOnScreen.Y, 0, 0);
            }
        });
    }
}
```

I'm opening and closing every 500ms, at the same time I'm simulating mouse click every 600ms. After letting it running a while it crashes at some point (less than 1 mn in my case). I only put random timing value, I don't really understand which timing makes it break. It also seems to break only with mouse click, not by changing the IsDialogOpen dependency property on the 2 timers.

I also tried with material design 2.6.0, same crash.

**Comment by sandrohanea** [comment] 2019-08-19 07:53
I have this problem too, I manage to reproduce it using double click on a Dialog's grayed area and CloseOnClickAway="True".

**Comment by sandrohanea** [comment] 2019-08-19 09:09
I made a PR with the fix for this issue: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1377

**Closed** 2019-09-03 05:06 UTC
Labels: bug
