### ISSUE TITLE
Resizing card in demo app

### ISSUE THREAD

**Issue by Erapchu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2577] opened 2022-02-11 03:50 UTC
Material Design Demo app -> Cards -> resizing card.
After resize card is out of bounds. Didn't check is it local issue or not, but it's exist in demo.

https://user-images.githubusercontent.com/37536541/153534709-3fba70a5-01e4-4334-9ef4-aa27822e8dc8.mp4

**Comment by greuelpirat** [comment] 2023-04-23 16:06
I could not reproduce the issue on the current master/head. But when I checked out 5881263a (tagged as `v4.8.0`) I could reproduce it. Looks to me this has been fixed. But to be honest I have found no change that I can link to this issue.

@mouawadma can you try if your issue still exists on the current head?

**Comment by greuelpirat** [comment] 2023-04-23 16:09
Ah, it is fixed with #3136

**Comment by greuelpirat** [comment] 2023-04-23 16:15
4554217e / #3118 fixed this

**Closed** 2023-04-24 16:39 UTC
Labels: bug
