### ISSUE TITLE
InvalidOperationException in TransitioningContent when loading user control 

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#345] opened 2016-04-19 13:53 UTC
This caused an exception when loading the UserControl/View.

```
<mdt:TransitioningContent VerticalAlignment="Bottom" RunHint="All" mahApps:VisibilityHelper.IsCollapsed="{Binding Enabled}">
            <mdt:TransitioningContent.OpeningEffects>
                <mdt:TransitionEffect Kind="FadeIn"/>
                <mdt:TransitionEffect Kind="SlideInFromBottom"/>
            </mdt:TransitioningContent.OpeningEffects>
            ...
</mdt:TransitioningContent>

```

Changing to `RunHint="IsVisibleChanged"` fixed it for me. However, I have been using `RunHint="All"` before without any problems. Dunno why this suddenly happened. Maybe a slow view/viewmodel combination.

```
System.InvalidOperationException: 'PART_TranslateTransform' name cannot be found in the name scope of 'MaterialDesignThemes.Wpf.Transitions.TransitioningContent'.
at System.Windows.Media.Animation.Storyboard.ResolveTargetName(System.String targetName, System.Windows.Markup.INameScope nameScope, System.Windows.DependencyObject element) at offset 143
at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(System.Windows.Media.Animation.Clock currentClock, System.Windows.DependencyObject containingObject, System.Windows.Markup.INameScope nameScope, System.Windows.DependencyObject parentObject, System.String parentObjectName, System.Windows.PropertyPath parentPropertyPath, System.Windows.Media.Animation.HandoffBehavior handoffBehavior, System.Collections.Specialized.HybridDictionary clockMappings, System.Int64 layer) at offset 164
at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(System.Windows.Media.Animation.Clock currentClock, System.Windows.DependencyObject containingObject, System.Windows.Markup.INameScope nameScope, System.Windows.DependencyObject parentObject, System.String parentObjectName, System.Windows.PropertyPath parentPropertyPath, System.Windows.Media.Animation.HandoffBehavior handoffBehavior, System.Collections.Specialized.HybridDictionary clockMappings, System.Int64 layer) at offset 481
at System.Windows.Media.Animation.Storyboard.BeginCommon(System.Windows.DependencyObject containingObject, System.Windows.Markup.INameScope nameScope, System.Windows.Media.Animation.HandoffBehavior handoffBehavior, System.Boolean isControllable, System.Int64 layer) at offset 127
at MaterialDesignThemes.Wpf.Transitions.TransitioningContentBase.RunOpeningEffects() at offset 156
at MaterialDesignThemes.Wpf.Transitions.TransitioningContent.<.ctor>b__1_0(System.Object sender, System.Windows.RoutedEventArgs args) at offset 0
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object target, System.Windows.RoutedEventArgs routedEventArgs) at offset 16
at System.Windows.EventRoute.InvokeHandlersImpl(System.Object source, System.Windows.RoutedEventArgs args, System.Boolean reRaised) at offset 230
at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args) at offset 87
at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs e) at offset 20
at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject root, System.Windows.RoutedEvent routedEvent) at offset 68
at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object root) at offset 37
at MS.Internal.LoadedOrUnloadedOperation.DoWork() at offset 8
at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks() at offset 42
at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() at offset 88
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object resizedCompositionTarget) at offset 92
at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object resizedCompositionTarget) at offset 46
at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget resizedCompositionTarget) at offset 49
at System.Windows.Interop.HwndTarget.OnResize() at offset 152
at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage msg, System.IntPtr wparam, System.IntPtr lparam) at offset 450
at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(System.IntPtr hwnd, System.Int32 msg, System.IntPtr wParam, System.IntPtr lParam, System.Boolean& handled) at offset 24
at MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, System.Int32 msg, System.IntPtr wParam, System.IntPtr lParam, System.Boolean& handled) at offset 8
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object o) at offset 54
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, System.Object args, System.Int32 numArgs) at offset 119
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object source, System.Delegate callback, System.Object args, Syst
```

**Comment by ButchersBoy** [comment] 2016-04-19 20:09
...interesting one....are you able to isolate in a test repo?

**Comment by mgnslndh** [comment] 2016-04-20 08:39
Let me see what I can come up with.

**Comment by cpyfferoen** [comment] 2019-11-20 22:06
I'm getting a very similar issue - but only since we went to .net core 3.0
Was running with the 2.6 release - thought moving up to the 3.0 ci builds would fix it - but it has not
Seems to be kinda random...

Including several stack traces - should be be found useful (to me or anyone when looking into this)

``` 
System.ArgumentNullException: Value cannot be null. (Parameter 'defaultDestinationValue')
   at System.Windows.Media.Animation.DoubleAnimationBase.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.AnimationClock.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue)

goes on for a while

at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MaterialDesignThemes.Wpf.DialogHost.set_DialogContent(Object value)
   at MaterialDesignThemes.Wpf.DialogHost.OpenDialogHandler(Object sender, ExecutedRoutedEventArgs executedRoutedEventArgs)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
```

```
System.AggregateException: One or more errors occurred. ('Root' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.)
 ---> System.InvalidOperationException: 'Root' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.
   at System.Windows.Media.Animation.Storyboard.ResolveTargetName(String targetName, INameScope nameScope, DependencyObject element)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)

more calls

   at System.Windows.DependencyObject.SetCurrentValue(DependencyProperty dp, Object value)
   at MaterialDesignThemes.Wpf.SnackbarMessageQueue.<>c__DisplayClass30_0.<ShowAsync>b__2()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at MaterialDesignThemes.Wpf.SnackbarMessageQueue.<>c__DisplayClass30_0.<<ShowAsync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at MaterialDesignThemes.Wpf.SnackbarMessageQueue.<>c.<ShowAsync>b__30_1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at MaterialDesignThemes.Wpf.SnackbarMessageQueue.ShowAsync(Snackbar snackbar, SnackbarMessageQueueItem messageQueueItem)
   at MaterialDesignThemes.Wpf.SnackbarMessageQueue.PumpAsync()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```
System.ArgumentNullException: Value cannot be null. (Parameter 'defaultDestinationValue')
   at System.Windows.Media.Animation.DoubleAnimationBase.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.AnimationClock.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue)

   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Controls.ContentControl.set_Content(Object value)
   at Prism.Regions.ContentControlRegionAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object <p0>, NotifyCollectionChangedEventArgs <p1>)
   at Prism.Regions.ViewsCollection.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Prism.Regions.ViewsCollection.NotifyRemove(IList items, Int32 originalIndex)

a bit more prism stuff
```

**Comment by cpyfferoen** [comment] 2019-11-20 22:19
Tried a little harder and can consistently reproduce - 
1. using a Snackbar, in a PopUp
1. If Closing the popup prior to Animation Finishing - Hard application crash
1. If Clsing after the Animation finishes - different exception - but application doesn't crash (for me at least)

**Comment by Keboo** [comment] 2021-09-24 05:21
It appears that the original crash has been fixed as the call stack no longer exists.
The second one does not appear to reproduce for me. If the second crash is still an issue please reopen as a separate issue.

**Closed by Keboo** 2021-09-24 05:21 UTC
