### ISSUE TITLE
Problem with DialogContent

### ISSUE THREAD

**Issue by 91270** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2209] opened 2021-01-09 07:53 UTC
The controls in DialogContent have shadows ，

![image](https://user-images.githubusercontent.com/61639203/104086431-f7bd1900-5292-11eb-8e7b-896e121b87fe.png)

**Version**

![image](https://user-images.githubusercontent.com/61639203/104086491-72863400-5293-11eb-8923-4a2d69890b03.png)

**Code**

> 

    <Material:DialogHost  x:Name="DataLoading" DialogTheme="Inherit">
        <Material:DialogHost.DialogContent>
            <StackPanel Width="400" Height="300">
                <TextBlock Text="DATA LOADING..."  Margin="0,50,0,0"  HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="22" FontWeight="Bold"></TextBlock>
                <ProgressBar x:Name="LoadingProgress" Margin="0,80,0,0" Style="{DynamicResource MaterialDesignCircularProgressBar}" HorizontalAlignment="Center" VerticalAlignment="Center" Height="50"  Width="50"  IsIndeterminate="True" Value="0" />
            </StackPanel>
        </Material:DialogHost.DialogContent>
        <Grid>

        </Grid>
    </Material:DialogHost>

**Comment by Erapchu** [comment] 2021-01-10 07:19
What if you try to not use mah apps window? Try to use common Window, not MetroWindow and show this dialog again.

**Comment by 91270** [comment] 2021-01-11 00:14
Thank you, after testing, remove the MahApps window, the display returns to normal

**Comment by Erapchu** [comment] 2021-01-11 02:42
I can't reproduce your issue with MahApps MetroWindow, please check that your merged dictionaries are correct.
You can find out all merged dictionaries here:
[App.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/App.xaml)

**Comment by 91270** [comment] 2021-01-11 08:26
![image](https://user-images.githubusercontent.com/61639203/104159143-c165d200-5429-11eb-83be-1c8459fa63be.png)

**Comment by 91270** [comment] 2021-01-14 00:26
Add           UseLayoutRounding = True
solved this problem

**Comment by Keboo** [comment] 2021-01-16 06:37
Great! Glad you were able to track down the issue. Closing for now as I don't believe there are any changed needed for this library.

**Closed by Keboo** 2021-01-16 06:37 UTC
