### ISSUE TITLE
Build of MaterialDesignDemo fails with ArgumentNullException in BuildXamlDictionaryTask

### ISSUE THREAD

**Issue by henon** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1147] opened 2018-12-17 19:02 UTC
With VisualStudio 2017, even after installing latest updates I can not compile MaterialDesignDemo:

Error The "BuildXamlDictionaryTask" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
at System.IO.Path.Combine(String path1, String path2)
at ShowMeTheXAML.MSBuild.BuildXamlDictionaryTask.BuildGeneratedFile(IEnumerable`1 pairs)
at ShowMeTheXAML.MSBuild.BuildXamlDictionaryTask.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() MaterialDesignDemo

I installed paket dependencies with ".paket/paket.exe install" but no luck
To be clear, this is the latest source from github: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/6e66b80e203cf25e5d66004484f56d33ab054125

I tried to update the dependencies as recommended in another issue like the following, but no luck:

nuget ShowMeTheXAML ~> 1.0.10-ci45
nuget ShowMeTheXAML.AvalonEdit ~> 1.0.10-ci45
nuget ShowMeTheXAML.MSBuild ~> 1.0.10-ci45

Anyone familiar with this error?

**Comment by Keboo** [comment] 2018-12-17 21:17
There is an error with the ShowMeTheXAML library that I will get addressed. 
The issue is that the paket restore is being kicked off by MSBuild. This downloads ShowMeTheXAML and adds the needed targets file. However because the default behavior is to keep the MSBuild process alive it never reloads the latest values. As a work around, simply closing and relaunching Visual Studio will solve the problem.

**Closed** 2018-12-18 05:57 UTC
Labels: bug

**Comment by jespersh** [comment] 2018-12-18 09:12
One thing I observed was this happened if the path was too long, like `C:\Users\jsh\Downloads\MaterialDesignInXamlToolkit-master2\MaterialDesignInXamlToolkit-master`.
Then moving it to `C:\temp\MaterialDesignInXamlToolkit-master` made it build

**Comment by Keboo** [comment] 2018-12-18 15:35
@jespersh can you test with the latest code to see if it is still a problem?

**Comment by henon** [comment] 2018-12-19 08:53
I tried again with your changes and it builds now for me. Thanks!

**Comment by jespersh** [comment] 2018-12-19 11:35
> @jespersh can you test with the latest code to see if it is still a problem?

It actually wont build if the path is too long it appears. There's seemingly not a lot to be learned from the build logs this time: https://gist.github.com/jespersh/4e65cd83b2d49ad686761d088d69741d

**Comment by henon** [comment] 2018-12-19 11:41
>  error : ShowMeTheXAML was added to the MaterialDesignDemo project. Please rebuild the project.

I had to hit build multiple times when starting with a fresh source, getting the same message. Did you try that?

**Comment by Keboo** [comment] 2018-12-19 16:46
Also worth pointing out, as the message indicates on a fresh clone after ShowMeTheXAML is added you do need to do a rebuild (Build >> Rebuild Solution). By default Visual Studio keeps the MSBuild process alive and running to keep things fast, but this can be problematic when a package containing an MSBuild task is added.

**Comment by jespersh** [comment] 2018-12-20 09:45
A rebuild of the previously built yesterday, worked this morning.
I kept using build instead of rebuild yesterday, since the error message told me to build and not rebuild.
