### ISSUE TITLE
TabControl - Option to get v4.4.0 default look in v4.5.0

### ISSUE THREAD

**Issue by avanbremen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2666] opened 2022-05-03 18:41 UTC
First of all, thanks for creating an awesome toolkit!

I noticed that the default look of the TabControl changed from version 4.4.0 to version 4.5.0. So far I did not find a way to replicate the 'old' design in the latest version. Setting `materialDesign:ColorZoneAssist.Background` and `Foreground` only affects the full-width fill. Setting `wpf:ColorZoneAssist.Mode` to for example `Standard` will result in a black text and underline. There is no Mode to replicate the v4.4.0 look.

As I already released my application with the 'old' v.4.4.0 design, it would be awesome if I could replicate this design in v.4.5.0 without overriding the entire TabControl Style. For example by being able to set a `HeaderForeground`.

![mdix-tabcontrol-v4-4-0](https://user-images.githubusercontent.com/25454736/166520627-991ba3a8-350f-471d-9f12-6084dc6243a0.jpg)
_Default TabControl in v4.4.0_

![mdix-tabcontrol-v4-5-0](https://user-images.githubusercontent.com/25454736/166520657-90afaca7-9889-480b-8e3c-c7fa2dec09e6.jpg)
_Default TabControl in v4.5.0_

Thanks and all the best,
Arjan

**Comment by mikechristiansenvae** [comment] 2022-07-12 21:25
FYI: I think this is a duplicate of #2660

**Closed** 2022-07-15 06:24 UTC
Labels: bug, evaluation required
