### ISSUE TITLE
StackOverFlow Exception when using DialogHost

### ISSUE THREAD

**Issue by mynameisthing** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#766] opened 2017-08-08 19:21 UTC
When I set the DataType for a DialogHost DataTemplate to system:String the application will crash with a Stackoverflow exception. If the DataType is set back to DateTime the issue no longer happens

I found this issue with the MainDemo.WPF project as well. I forked and made the changes in the repository below.
https://github.com/akallenbach/MaterialDesignInXamlToolkit

The only Exception text I was able to get was this
```
System.StackOverflowException occurred
  HResult=0x800703E9
```

**Comment by mgnslndh** [comment] 2021-10-30 12:24
Not sure this is fixable? Override the "global" DataTemplate for System.String will cause a StackOverflowException if that template tries to render a string. I guess this is to be expected. So, If you remove string rendering from that template in the demo it will work but we've essentially broken string rendering:

```
<!-- data template used for the dialogs example, defines a View for a ViewModel of type DateTime  -->
<DataTemplate DataType="{x:Type system:String}">
    <StackPanel Margin="16">
        <!--<TextBlock Text="England win the World Cup:"/>
        <TextBlock Margin="0 8 0 0" Text="{Binding}"/>
        <TextBlock Margin="0 8 0 0" Text="You will never see that again."/>-->
        <Button
            Margin="0 8 0 0"
            IsDefault="True"
            Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}"
            Style="{DynamicResource MaterialDesignFlatButton}"
            />
    </StackPanel>
</DataTemplate>
```

![image](https://user-images.githubusercontent.com/1139118/139532676-172c8785-ce47-422b-a734-4fca893af95d.png)

I guess you should not override the string template.

**Comment by mgnslndh** [comment] 2021-10-30 12:29
The StackOverflowException is probably caused by the Button which had a string content that needed to be rendered. If you're going to override the string template you it needs to be a simple template like:

```
<DataTemplate DataType="{x:Type system:String}">
    <TextBlock Text="{Binding}" />
</DataTemplate>
````

But you probably don't want that either because all strings will be affected.

**Comment by mgnslndh** [comment] 2021-10-30 12:30
I'd say we close this issue.

**Comment by Keboo** [comment] 2021-10-30 15:49
Agree. Will close for now unless someone wants to come up with an alternate proposal for this

**Closed by Keboo** 2021-10-30 15:49 UTC
Labels: bug, up-for-grabs
