### ISSUE TITLE
Warning: 40 : BindingExpression RichTextBox

### ISSUE THREAD

**Issue by Ares-87** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2501] opened 2021-11-25 00:49 UTC
Hi all,
I have this error with RichTextBox with latest version of MaterialDesign Toolkiot, anyone have an idea how solve this?
Thank you

```
System.Windows.Data Warning: 40 : BindingExpression path error: 'Text' property not found on 'object' ''RichTextBox' (Name='textPlayerLogs')'. BindingExpression:Path=Text.Length; DataItem='RichTextBox' (Name='textPlayerLogs'); target element is 'TextBlock' (Name='CharacterCounterTextBlock'); target property is 'Text' (type 'String')
System.Windows.Data Warning: 40 : BindingExpression path error: 'MaxLength' property not found on 'object' ''RichTextBox' (Name='textPlayerLogs')'. BindingExpression:Path=MaxLength; DataItem='RichTextBox' (Name='textPlayerLogs'); target element is 'TextBlock' (Name='CharacterCounterTextBlock'); target property is 'Text' (type 'String')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.TextBox', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'TextBlock' (Name='CharacterCounterTextBlock'); target property is 'Visibility' (type 'Visibility')
```

**Comment by Keboo** [comment] 2021-11-25 05:01
I believe this is a duplicate of #2462. This should already be fixed in the latest preview releases and will be going out as part of the 4.3.0 release.

**Comment by Ares-87** [comment] 2021-11-25 13:53
> I believe this is a duplicate of #2462. This should already be fixed in the latest preview releases and will be going out as part of the 4.3.0 release.

Thank you.

**Comment by MichelMichels** [comment] 2021-12-26 18:36
Closed due to fix

**Closed by MichelMichels** 2021-12-26 18:36 UTC
Labels: bug, duplicate
