### ISSUE TITLE
Dear developer, A serious problem with the DialogHost

### ISSUE THREAD

**Issue by peijiehuang** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3085] opened 2023-02-14 06:47 UTC
### Bug explanation

Dear developer

Because my English is not good, I need to borrow translation software. I hope you can understand.

The DialogHost Normal is no problem，But once the software is placed on the server and remote control server，When DialogHost After pop-up message box，Disconnect the remote server and then restart the remote server，the interface cannot be operated。

At first, I thought it was caused by my code problem, but I will test your code and cause this problem。

Thank you, great programmer，Your frame is convenient for me。

![normal](https://user-images.githubusercontent.com/82989313/218659996-7a0d2de8-9dfc-4c40-97bb-d0b91053781d.png)

![2](https://user-images.githubusercontent.com/82989313/218660045-8e8fe42e-8d2d-4c61-b0c1-e28508cc710c.png)

### Version

4.6.1

**Comment by peijiehuang** [comment] 2023-02-14 06:54
In addition, there will be problems whenever DialogHost is used

My guess is that after reconnecting the remote, the interface has been refreshed, and the information box is not at the top, resulting in the interface being inoperable

**Comment by peijiehuang** [comment] 2023-02-14 07:10
Dear programmer, it is reconnecting the remote, not restarting the system.

**Comment by Keboo** [comment] 2023-02-14 08:04
Thank you for this report, however this appears to be a duplicate of #3069

**Closed by Keboo** 2023-02-14 08:04 UTC
Labels: bug, evaluation required
