### ISSUE TITLE
MaterialDesignThemes v2.5.0.1205 fails where MaterialDesignThemes v2.3.1.953 works

### ISSUE THREAD

**Issue by DassoParis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1159] opened 2019-01-05 21:17 UTC
Hello,

MaterialDesign is amazing and I want to help to make it better,

I have created a repository on github that illustrates that the same code works with MaterialDesignThemes v2.3.1.953 but don't compile with MaterialDesignThemes v2.5.0.1205. 

Check this repository: https://github.com/DassoParis/MaterialDesignThemes

- master branch: ok
- Update-to-MaterialDesignThemes-v2.5.0.1205-package branch: fail

**Comment by Keboo** [comment] 2019-01-07 18:18
@DassoParis thank you for the reproduction repo. The issue is fixed in the latest code and will go out with the next preview NuGet package.

**Closed** 2019-01-07 18:17 UTC
Labels: bug
