### ISSUE TITLE
New demo - source code issues

### ISSUE THREAD

**Issue by Symbai** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#861] opened 2017-12-08 12:49 UTC
The new demo has two issues:

- The copy button does not copy the whole text if the user has have any text selected.
- The source code view jumps around if you scroll

![untitled project](https://user-images.githubusercontent.com/14368203/33766611-9b8deb20-dc1e-11e7-932d-0a1d1ffee13e.gif)

**Comment by wongjiahau** [comment] 2017-12-08 14:47
@Symbai I had written the code such that the copy button will only copy those selected text, so it is not a bug, it is expected to behave like that. 

However for the second problem, it is definitely a bug, if there's a lot of other people complaining this I will fix this issue. 

Thanks for the feedback 😄

**Comment by LinkinForEver** [comment] 2017-12-31 22:22
What is that demo ?

I developed a plugin with a similar thing to this but that was ok 👍 : 
<img src="https://www.imageupload.co.uk/images/2017/12/31/X.gif" border="0">

**Comment by Keboo** [comment] 2018-07-27 16:16
No longer an issue. Closing.

**Closed by Keboo** 2018-07-27 16:16 UTC
