### ISSUE TITLE
WPF context menu backgrounds broken in 4.4.0

### ISSUE THREAD

**Issue by BigBadBleuCheese** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2611] opened 2022-03-21 19:14 UTC
I first noticed this in my own app, but it is also present in the demo app, so it should be pretty easy to review. I'm including some screenies anyway.

The default context menu under the **Menus and Toolbars** section:
![image](https://user-images.githubusercontent.com/25014958/159346850-9cae0a40-5261-4206-ab7b-b9b85453efc7.png)

Right-clicking the **Search** box in navigation:
![image](https://user-images.githubusercontent.com/25014958/159347012-43b10632-3098-4932-baee-3026063e4b56.png)

**Comment by Keboo** [comment] 2022-03-21 19:17
This looks like it is a duplicate of #2606 (PR fixed a few hours ago, and will be in the nightly release tonight).

**Closed as completed by Keboo** 2022-03-21 19:17 UTC
Labels: duplicate
