### ISSUE TITLE
Combobox and Pickers Bug

### ISSUE THREAD

**Issue by tkacleonid** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1972] opened 2020-07-09 14:44 UTC
When I use combobox and pickers, I see dotted line under the disabled controls. How can I fix it?

In first Tab combobxes and pickers disabled:

![изображение](https://user-images.githubusercontent.com/5224727/87053926-305c3700-c20b-11ea-8c9b-fdbb68c872f2.png)

In other tabs I can see dottend line when disabled controls have places on the first tab:

![изображение](https://user-images.githubusercontent.com/5224727/87054423-c1cba900-c20b-11ea-980f-015d1a610f34.png)

**Comment by Keboo** [comment] 2020-07-10 03:39
I believe this is a duplicate of #1840. Please test with the 3.2.0 _preview_ NuGet packages and it should be resolved.

**Closed** 2020-09-11 05:51 UTC
Labels: bug, duplicate
