### ISSUE TITLE
Clock am/pm lost with seconds display

### ISSUE THREAD

**Issue by jespersh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1154] opened 2018-12-25 11:28 UTC
![2018-12-25-12-25-34](https://user-images.githubusercontent.com/1004198/50421482-357fae00-0840-11e9-9b22-dd918eafa8d4.gif)

Using the demo it is possible to lose the am/pm status of a field and convert a 11pm to a 11am when flipping 24h->12h clock

**Comment by stigrune** [comment] 2019-01-16 18:11
I’m not able to reproduce this bug in master or in latest version 2.5.0. Do you have a way to trigger this bug consistently?

**Comment by jespersh** [comment] 2019-01-17 09:15
Downloaded the master right now and I can reproduce it there.

Here are the OS (Danish language, Danish locale) settings at work.
![tilgithub](https://user-images.githubusercontent.com/1004198/51307701-a3368880-1a40-11e9-8d1b-feb7da93f233.PNG)

Might retry it at home where my OS language is English, but with Danish locale.
I think it could have something to do with these settings.

**Comment by stigrune** [comment] 2019-01-17 13:38
Thank you, I was able to reproduce this changing my “Region -> Format” to Danish (English OS display language).

**Comment by stigrune** [comment] 2019-01-17 19:47
Did some testing and this is not a bug in MaterialDesignInXamlToolkit TimePicker logic, but rather with the Danish locale in .NET. The Danish DateTimeFormatInfo is missing AMDesignator and PMDesignator values.

Can be verified like this in a console app:
```C#
var datetime = DateTime.Now;
var dtfNo = new CultureInfo("nb-NO", false).DateTimeFormat;
var dtfDk = new CultureInfo("da-DK", false).DateTimeFormat;

Console.WriteLine($"NO: AMDesignator: {dtfNo.AMDesignator} PMDesignator: {dtfNo.PMDesignator}");
Console.WriteLine(datetime.ToString("h:mm:ss tt", dtfNo));

Console.WriteLine($"DK: AMDesignator: {dtfDk.AMDesignator} PMDesignator: {dtfDk.PMDesignator}");
Console.WriteLine(datetime.ToString("h:mm:ss tt", dtfDk));

Console.ReadLine();
```
Output:
```
NO: AMDesignator: a.m. PMDesignator: p.m.
8:44:19 p.m.
DK: AMDesignator:  PMDesignator:
8:44:19
```
Maintainers should decide if this is something they want to handle in the TimePicker.DateTimeToString method.

**Comment by Keboo** [comment] 2021-09-25 19:20
Appears fixed in the latest version of the code.
![image](https://user-images.githubusercontent.com/952248/134783786-4089e6b6-6c8e-4b14-80b1-92f6408c6bb5.png)

**Closed by Keboo** 2021-09-25 19:20 UTC
